Feat/added-varslinger-i-topbar
TIHLDE/Kvark pull request #181
Opened 2021-09-18 00:06 UTC by callumgran

## Description
La til icon i topbar og popup meny for varslinger.
closes #

Changes:
Endret bredde til .right klassen i Topbar.tsx
Endringer i filen ProfileTopbarButton.tsx for å legge til popupmeny og icon for varslinger.
Lagde fil som heter TopbarNotifications.tsx basert på ProfileNotifications.tsx for å få notifications i popup menyen.
Screenshots:
![image](https://user-images.githubusercontent.com/89872274/133864854-d79d8aef-3c02-4f8b-bd85-3b07ec09917b.png)
![image](https://user-images.githubusercontent.com/89872274/133864869-42d4d963-d152-4b09-84d4-41455a7648d5.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [Vet ikke hva dette betyr, men gjør det som etterspørres.] The PR includes a `closes #issueID`
- [Check] The PR includes a picture showing visual changes
- [Tja ish] Added Google Analytics tracking if relevant
- [Yup] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [Tror den gjør dette automatisk etter det jeg har lest] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2021-09-18 15:38 UTC, Her0elt reviewed
varslingene burde ikke dukke opp når man ikke er logget inn, og @olros er det sånn vi tenker det burde være deignet eller tenker vi mer en drop down og ikke popup

![image](https://user-images.githubusercontent.com/60223374/133894270-1cb9d097-fd18-4939-902f-05a2f7103b93.png)

2021-09-18 15:52 UTC, olros requested changes
Good catch at varsler ikke skal vises når ikke innlogget @Her0elt !

Ift utseende så tenker jeg at en dialog som nå funker bra på mobil, kanskje vi skal gjøre den `fullScreen`. På større skjermer så tror jeg det er bedre med en dropdown løsning som kan være ish slik som Facebook sin løsning.

I tillegg kan vi også fjerne varsler fra profilen når de kommer her istedenfor.

Ellers er det helt supert jobba @callumgran ! Vi kan jobbe oss gjennom endringene sammen på neste møte. Dropdown menyer kan være ganske tricky 😉

2021-09-18 15:52 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +const NotifcationsTopBar = ({ onClose, open }: NotificationTopBarProps) => {
Skrivefeil ;)

```suggestion
const NotificationsTopBar = ({ onClose, open }: NotificationTopBarProps) => {
```

2021-09-18 15:52 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +    maxWidth: '600px',
Tror du kan sette `maxWidth='md'` som prop på Dialog istedenfor å style selv

2021-09-18 15:52 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +type NotificationTopBarProps = {
Eksporter gjerne type til props på komponenter som eksporteres fra en fil

```suggestion
export type NotificationTopBarProps = {
```

2021-09-18 15:52 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +          Meldinger
Hvis vi skal ha en overskrift så ville jeg kanskje kalt den "Varsler" istedenfor

2021-09-18 15:52 UTC, olros commented on src/components/navigation/ProfileTopbarButton.tsx
> +import NotifcationsTopBar from 'components/miscellaneous/TopbarNotifications';
Skrivefeil ;)

2021-09-18 15:52 UTC, olros commented on src/components/navigation/ProfileTopbarButton.tsx
> +  const notificationsBadge = { icon: NotificationsIcon, badge: user?.unread_notifications };
Nle grunn til at du lager dette objektet og ikke bare bruker variablene direkte?

2021-09-18 15:52 UTC, olros commented on src/components/navigation/ProfileTopbarButton.tsx
> +      <IconButton aria-label='Vis meldinger' className={classes.themeButton} onClick={() => setShowNotifcationItem(true)}>
```suggestion
      <IconButton aria-label='Vis varsler' className={classes.themeButton} onClick={() => setShowNotifcationItem(true)}>
```

2021-09-18 15:52 UTC, olros commented on src/components/navigation/Topbar.tsx
> +    gridTemplateColumns: '170px 1fr 172px', //*Her har jeg endret med 2px for å få plass til alle 3 ikoner til høyre
Hvis du legger til 2px på begge sider så vil vel menyen fremdeles være sentrert. Du trenger heller ikke legge inn kommentar i koden på slike endringer. Hvis det er nyttig for reviewer å vite grunn til en endring (slik som her), så kan du for eks heller legge til en kommentar som dette 🚀 

```suggestion
    gridTemplateColumns: '172px 1fr 172px',
```

2021-09-22 14:39 UTC, olros requested changes
Nærmer seg veldig! Litt småplukk i kommentarene også fjerne varsler fra profilen så bør du være i mål!

2021-09-22 14:39 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +import { useEffect, useState, useMemo, useRef } from 'react';
Tenker denne filen kan flyttes til `/Navigation` mappen der Topbar ligger

2021-09-22 14:39 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +  const [showNotificationItem, setShowNotificationItem] = useState(false);
Mer presis navngivning:

```suggestion
  const [showNotifications, setShowNotifications] = useState(false);
```

2021-09-22 14:39 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +  const anchorRef = useRef<HTMLButtonElement>(null);
Bedre navn

```suggestion
  const buttonAnchorRef = useRef<HTMLButtonElement>(null);
```

2021-09-22 14:39 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +  };
```suggestion
  const NotificationsList = () => (
      <>
        <Typography align='center' gutterBottom variant='h2'>
          Varslinger
        </Typography>
        {isLoading && <NotificationItemLoading />}
        {isEmpty && <NotFoundIndicator header='Fant ingen varsler' />}
        {error && <Paper>{error.detail}</Paper>}
        {data !== undefined && (
          <Pagination fullWidth hasNextPage={hasNextPage} isLoading={isFetching} nextPage={() => fetchNextPage()}>
            <List dense disablePadding>
              {notifications.map((notification) => (
                <NotificationItem key={notification.id} notification={notification} />
              ))}
            </List>
          </Pagination>
        )}
        {isFetching && <NotificationItemLoading />}
      </>
    );
```

2021-09-22 14:39 UTC, olros commented on src/components/miscellaneous/TopbarNotifications.tsx
> +              }}>
```suggestion
              style={{ transformOrigin: 'right top' }}>
```

2021-09-22 14:39 UTC, olros commented on src/components/navigation/Topbar.tsx
> +    justifyContent: 'space-evenly',
La denne forbli `flex-end` så man slipper så stor endring i layout når man går fra å ikke være logget inn til å være logget inn

2021-09-27 19:18 UTC, callumgran commented
Ikke tenk på siste pushen

2021-09-28 19:10 UTC, olros approved these changes
Herlig jobba! Ser bra ut!

2021-09-29 06:23 UTC, merged