Feature/adding tooltip in on userinputs
TIHLDE/Kvark pull request #188
Opened 2021-09-21 17:18 UTC by MartinClementz

## Description

closes #145 

Changes: Legger til en ny komponent, Tooltip. Denne komponenten skal gi nye brukere informasjon om hva de skal skrive inn.

Screenshots:
<img width="934" alt="Skjermbilde 2021-09-21 kl  19 11 59" src="https://user-images.githubusercontent.com/26656069/134216630-2bcdeea3-5347-4029-b50a-e269949892bf.png">
<img width="917" alt="Skjermbilde 2021-09-21 kl  19 12 10" src="https://user-images.githubusercontent.com/26656069/134216595-fb35179c-8664-44b6-8953-adf10b123f1c.png">

## Pull re

quest checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes
- [ ] Added Google Analytics tracking if relevant
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2021-09-21 17:36 UTC, MartinClementz commented
Nå kan er det en props i TextField som heter tooltip. 

<img width="916" alt="Skjermbilde 2021-09-21 kl  19 35 26" src="https://user-images.githubusercontent.com/26656069/134219886-c70ffbd9-bb60-45c4-be4c-887703888de5.png">

<img width="982" alt="Skjermbilde 2021-09-21 kl  19 35 31" src="https://user-images.githubusercontent.com/26656069/134219862-21086c0c-bbc6-4f96-8880-2950913fe9a3.png">

2021-09-21 18:05 UTC, olros requested changes
Kult! Jeg tenker at `<ToolTop />` er knallbra og bør legges til i `miscellaneous`-mappen. Se hva som kan gjøres ekstra i den.

Ift å legge til en `tooltip: String` prop i TextField og Select så tror jeg ikke det er så lurt. Det å legge til tooltip i komponenter for generell bruk uten at det nødvendigvis er viktig veldig ofte er unødvendig. Da kan heller den som ønsker det gjøre det på for eks denne måten:

```jsx
<div>
  <TextField />
  <ToolTip />
</div>
```

Da slipper vi å endre en komponent for å bruke ToolTip.

2021-09-21 18:05 UTC, olros commented on src/components/layout/ToolTip.tsx
> +};
Ta inn TooltipProps fra `@mui` slik at vi kan alle Tooltip sine props

```suggestion
import { Tooltip as MuiTooltip, TooltipProps as MuiTooltipProps } from '@mui/material/Tooltip';
import { HelpOutline } from '@mui/icons-material';

export type TooltipProps = MuiTooltipProps;

const Tooltip= (props: MuiTooltipProps) =>  (
    <MuiTooltip arrow={true} placement='top' {...props}>
      <HelpOutline />
    </MuiTooltip>
  );
```

2021-09-21 18:09 UTC, MartinClementz commented
> Kult! Jeg tenker at `<ToolTop />` er knallbra og bør legges til i `miscellaneous`-mappen. Se hva som kan gjøres ekstra i den.
> 
> Ift å legge til en `tooltip: String` prop i TextField og Select så tror jeg ikke det er så lurt. Det å legge til tooltip i komponenter for generell bruk uten at det nødvendigvis er viktig veldig ofte er unødvendig. Da kan heller den som ønsker det gjøre det på for eks denne måten:
> 
> ```js
> <div>
>   <TextField />
>   <ToolTip />
> </div>
> ```
> 
> Da slipper vi å endre en komponent for å bruke ToolTip.

Supert! Da fikser jeg det!

2021-09-22 13:55 UTC, olros commented
Har ombestemt meg, sorry :/ Ser nå at `<Tooltip />` som importeres fra `@mui` er så enkel å bruke direkte at jeg ikke helt ser behovet for en egen komponent som wrapper et spørsmål-ikon. Mer fleksibelt å kunne legge den allerede ferdiglagde Tooltip'en rundt akkurat det innholdet en måtte ønske (for eks tekst, ikoner eller bilder).

Sånn jeg ser det går da #145 mer ut på å faktisk gjøre det: legge til ekstra info i tooltips der dagens forklaringer (eller ikke-eksisterende forklaringer) ikke er gode nok.

Tanker? Uenig?

Hvis enig så forslår jeg at denne PR'en kan closes.

2021-09-22 14:44 UTC, MartinClementz commented
> Har ombestemt meg, sorry :/ Ser nå at `<Tooltip />` som importeres fra `@mui` er så enkel å bruke direkte at jeg ikke helt ser behovet for en egen komponent som wrapper et spørsmål-ikon. Mer fleksibelt å kunne legge den allerede ferdiglagde Tooltip'en rundt akkurat det innholdet en måtte ønske (for eks tekst, ikoner eller bilder).
> 
> Sånn jeg ser det går da #145 mer ut på å faktisk gjøre det: legge til ekstra info i tooltips der dagens forklaringer (eller ikke-eksisterende forklaringer) ikke er gode nok.
> 
> Tanker? Uenig?
> 
> Hvis enig så forslår jeg at denne PR'en kan closes.

Jeg er både litt enig og litt uenig... Hovedsaklig på grunn av at jeg mener alle filene i `./src/pages` bør være så korte og presise som mulig for å gjøre dem lette å lese. Spørsmålikon med tooltip er noe man kan bruke overalt på admin-sidene, og gir nye admins klar beskjed om at **her** kan de få mere info. Men veldig enig at det er en ganske liten wrapper. I tillegg var det ikke akkurat hva bildene i #145 refererte til... en av grunnene til at dette var en draft :)

2021-09-22 14:44 UTC, closed without merging