Refactor(Admin edit): added spacing over and under buttons on admin edit pages
TIHLDE/Kvark pull request #216
Opened 2021-09-29 12:19 UTC by callumgran

## Description
Mere margin over og under knapper på NewsEditor, UpdateGroupModal og JobPostEditor slik at alt er samstemt.
closes #

Changes:
Lagt til class margin i verify dialog i filene JobPostEditor og NewsEditor.
La til usestyles og margin class og deretter plasserte class margin på Submitbutton i UpdateGroupModal.

Screenshots:
NewsEditor og JobPostEditor:
![image](https://user-images.githubusercontent.com/89872274/135266926-f23872ed-8704-4295-a291-9928397b3be3.png)

UpdateGroupModal:
![image](https://user-images.githubusercontent.com/89872274/135267064-24adae70-7968-49c6-b90e-204af1525dcd.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a `closes #issueID`
- [Check] The PR includes a picture showing visual changes
- [ ] Added Google Analytics tracking if relevant
- [Check] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2021-09-29 14:13 UTC, olros requested changes

2021-09-29 14:13 UTC, olros commented on src/pages/GroupAdmin/components/UpdateGroupModal.tsx
> +          <SubmitButton className={classes.margin} disabled={updateGroup.isLoading} formState={formState}>
Istedenfor `className` så kan du heller bruker `sx`-prop'en siden du kun trenger en marginTop. Da kan du også fjerne useStyles
```suggestion
          <SubmitButton sx={{ mt: 2 }} disabled={updateGroup.isLoading} formState={formState}>
```

2021-09-29 14:16 UTC, callumgran commented on src/pages/GroupAdmin/components/UpdateGroupModal.tsx
> +          <SubmitButton className={classes.margin} disabled={updateGroup.isLoading} formState={formState}>
Will do!

2021-10-05 16:35 UTC, olros approved these changes

2021-10-05 16:35 UTC, olros commented on CHANGELOG.md
> +- 🎨 **Edit panel**. Endret spacing på diverse knapper i edit paneler.
```suggestion
- 🎨 **Admin**. Endret spacing på diverse knapper i adminsider.
```

2021-10-05 19:05 UTC, merged