Feature/usereventpicture
tihlde/Kvark pull request #222
Opened 2020-09-07 17:14 UTC by henriettebs

# PR NAME
![Lint, test and build](https://github.com/tihlde/Kvark/workflows/Lint,%20test%20and%20build/badge.svg)
## Description
Link to Trello task: ...

Comments/issues/screenshots:
#204 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ ] `yarn build` was run locally without errors
- [ ] `yarn test` has passed locally and any fixes were made for failures
- [ ] `yarn format` was run locally and fixes were made for new errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-08 07:16 UTC, olros requested changes

2020-09-08 07:16 UTC, olros commented on src/containers/EventAdministration/components/EventParticipant.js
> +        {user.agree_photo && <Typography>Vil ikke bli tatt bilde av</Typography>}
Vi gjorde en feil her. "Vil ikke bli tatt bilde av" skal vises hvis `agree_photo` er `false` så da må vi endre `user.agree_photo` til `!user.agree_photo`

2020-09-12 19:43 UTC, Zenjjim commented on src/containers/EventDetails/components/EventDialog.js
> +                  label='Jeg godtar å bli tatt bilde av på arrangementet'
Jeg godtar at bilder av meg kan deles på TIHLDE sine plattformer

2020-09-15 18:33 UTC, olros approved these changes
Ser bra ut! 💯 

For å merge dette inn i dev-branchen vil jeg gjerne at du bruker "Squash and merge" slik at commitsene i denne branchen samles til 1 commit i dev:
![image](https://user-images.githubusercontent.com/31009729/92467076-51241700-f1d1-11ea-8d41-b596b4ed9b03.png)

Mulig du må trykke på "Update branch" først slik at branchen er oppdatert mot dev først.

2020-09-17 12:49 UTC, Zenjjim commented
Er dette koblet opp til backend?

2020-09-17 12:51 UTC, Zenjjim commented
feltet i backend heter `allow_photo`,så og er i prod så bare å koble seg opp :D

2020-09-17 12:51 UTC, olros commented
> Er dette koblet opp til backend? @henriettebs @olros 

Avhenger av tihlde/API#128 som du nettop merget ja

2020-09-20 12:24 UTC, merged