Fix/Changed errorhandling for authservice
tihlde/Kvark pull request #228
Opened 2020-09-12 15:28 UTC by superspeed500

# Changed the authservice to throw an custom error object instead of just loading indefinitely.
![Lint, test and build](https://github.com/tihlde/Kvark/workflows/Lint,%20test%20and%20build/badge.svg)
## Description
Link to Trello task: #219 

Comments/issues/screenshots:
Error handling for authservice is now changed. The code will throw an custom error object when backend returns 500.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [x] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [x] `yarn build` was run locally without errors
- [x] `yarn test` has passed locally and any fixes were made for failures
- [x] `yarn format` was run locally and fixes were made for new errors

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-12 19:39 UTC, Zenjjim requested changes
Noen endringer må skje i denne PR-en. Tror det blir feil å gjøre endringen i denne filen. Mener dette burde gjøres i isError funksjonen/flagget

2020-09-12 19:39 UTC, Zenjjim commented on src/api/services/AuthService.js
> +        }
Selv om vi kaster feilmelding, så sender vi nyttig data fra backend. Anbefaler å sende data og en error flag som kan vises til bruker. F.eks. "Wrong login credentials", "CTRF-token" osv

2020-09-12 19:39 UTC, Zenjjim commented on src/api/services/AuthService.js
> +      });
Hvorfor la du  inn denne? Vil ikke responde.isError kaste feil?

2020-09-12 19:39 UTC, Zenjjim commented on src/api/services/AuthService.js
> +      });
evt så burde isError fikses og ikke legge til mer kompleksitet til funksjonen.

2020-09-12 19:55 UTC, superspeed500 commented on src/api/services/AuthService.js
> +        }
Feilmeldingen er en 500 som returnerer HTML-kode. Må finne ut hvordan vi skriver om det til et dataobjekt isåfall.

2020-09-12 20:01 UTC, superspeed500 commented on src/api/services/AuthService.js
> +      });
Response returnerer et _promise_. Dersom baksystemet gir data i form av et objekt vil koden for suksess kjøres uavhengig av hvilken feilkode baksystemet returnerer. Dersom baksystemet gir data som ikke AUTH.authenticate forstår (som f.eks HTML-kode) vil AUTH. authenticate() krasje. Dersom det skjer vil vi få en loop med innloggingen slik vi har per i dag. La derfor til en catch() for å håndtere untakstilfeller der baksystemet ikke gir rett data. Men kan godt flytte denne sjekken til AUTH.authenticate() slik at det håndteres der og ikke i AuthService :)

2020-09-17 12:30 UTC, Zenjjim approved these changes

2020-09-22 11:51 UTC, merged