feat(listitem): create generic listitem component
tihlde/Kvark pull request #234
Opened 2020-09-16 17:26 UTC by olros

# feat(listitem): create generic listitem component
![Lint, test and build](https://github.com/tihlde/Kvark/workflows/Lint,%20test%20and%20build/badge.svg)
## Description

Comments/issues/screenshots:
closes #206 
closes #227 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [x] `yarn build` was run locally without errors
- [x] `yarn test` has passed locally and any fixes were made for failures
- [x] `yarn format` was run locally and fixes were made for new errors

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-17 09:58 UTC, olros commented on src/components/miscellaneous/ListItem.js
> +  const classes = useStyles();
Alle filer bør endres til å bruke styles på denne måten med hooks

2020-09-17 09:58 UTC, olros commented on src/components/miscellaneous/ListItem.js
>      borderRadius: theme.sizes.border.radius,
Kan vurdere å legge inn en default bakgrunns-farge for png'er slik at logoer ikke forsvinner i darkmode slik som på karriere i dag:
![image](https://user-images.githubusercontent.com/31009729/93455493-b9af7a00-f8dc-11ea-8070-2dd50ab41191.png)

Må bare finne en god farge

2020-09-17 09:58 UTC, olros commented on src/components/miscellaneous/ListItem.js
> +  ),
Kan vurdere å legge til en `imgContain`-prop som setter `objectFit: contain` i bildet for å sikre at hele bildet vises på for eks karriere siden

2020-09-17 12:33 UTC, Zenjjim commented on src/components/miscellaneous/ListItem.js
> +  const classes = useStyles();
Helt enig, blir mye mer leselig v.h.a hooks

2020-09-17 12:47 UTC, Zenjjim requested changes

2020-09-17 12:47 UTC, Zenjjim commented on src/components/miscellaneous/ListItem.js
> +  const src = img ? img : TIHLDELOGO;
`const src = img || TIHLDELOGO`

2020-09-17 12:47 UTC, Zenjjim commented on src/components/miscellaneous/ListItem.js
> +  const src = img ? img : TIHLDELOGO;
eller `??`

2020-09-17 12:47 UTC, Zenjjim commented on src/components/miscellaneous/ListItem.js
> +        {info && info.map((item, index) => <InfoContent icon={item.icon} key={index} label={item.label} />)}
trenger du `info &&`, er vel bedre å sjekke `info?.map`

2020-09-17 12:47 UTC, Zenjjim commented on src/containers/Events/index.js
> +                      {events &&
samme `event?.map`

2020-09-17 12:47 UTC, Zenjjim commented on src/containers/NewLanding/components/CalendarListView.js
> +              // return <ListItem data={eventData} key={index} />;
bruh

2020-09-17 12:47 UTC, Zenjjim commented on src/containers/News/index.js
> +                      displayedNews.map((newsItem) => (
same

2020-09-17 12:47 UTC, Zenjjim commented on src/containers/Profile/components/ProfileEvents.js
> +          if (event.expired === false) {
`!event.expired`

2020-09-17 12:56 UTC, olros commented on src/containers/NewLanding/components/CalendarListView.js
> +              // return <ListItem data={eventData} key={index} />;
ahaha

2020-09-20 16:36 UTC, Zenjjim approved these changes

2020-09-20 16:40 UTC, merged