Origin/refactor/typescript/max
tihlde/Kvark pull request #251
Opened 2020-10-05 16:07 UTC by maxschau

![Lint, test and build](https://github.com/tihlde/Kvark/workflows/Lint,%20test%20and%20build/badge.svg)
## Description

Comments/issues/screenshots:
#243 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes

## Typescript convert checklist

- [ ] All relative imports has been converted to absolute imports
- [ ] All HOC's have been replaced with Hooks
- [ ] Uses theme.spacing() instead of custom padding
- [ ] Uses theme.breakpoints instead of custom media queries

2020-10-07 12:52 UTC, olros requested changes
Alle `withStyles` må byttes ut med `useStyles`-hooken slik som det er gjort i `ListItem.tsx`. Da slipper du å gi type til classes. Vet ikke om vi ble enige om å exportere type'sene men tror ikke det skader å gjøre det. Ellers er det bra jobba 💯

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ClickableImage.tsx
> +export default withStyles(styles)(ClickableImage);
Bytt ut `withStyles` med `useStyles`-hooken. Da slipper du også `type CSSStyling`

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/DropdownButton.tsx
>  import Paper from '../layout/Paper';
Bruk absolutt import

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/DropdownButton.tsx
>  export default withStyles(styles)(DropdownButton);
Bytt til useStyles

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/DropdownButton.tsx
> +          <Button onClick={options[selectedIndex].func} ref={anchorRef} type='submit'>
Hvorfor bytter du element som ref er på her?

Se https://material-ui.com/components/button-group/#split-button for å se hvordan Material UI implementerer denne i Typescript. Da kan vi også unngå `event: any` på linje 61.

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/Emoji.tsx
> +    <span aria-hidden={label ? 'false' : 'true'} aria-label={label ? label : ''} className='emoji' role='img' style={{ color: 'black' }}>
```suggestion
    <span aria-hidden={!Boolean(label)} aria-label={label || ''} className='emoji' role='img' style={{ color: 'black' }}>
```

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/Emoji.tsx
> +    <span aria-hidden={label ? 'false' : 'true'} aria-label={label ? label : ''} className='emoji' role='img' style={{ color: 'black' }}>
Og vil ikke label alltid være `true` siden den er required?

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
>  import TIHLDELOGO from '../../assets/img/TihldeBackgroundNew.png';
Bruk absolutt import

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.down('xs')]: {
```suggestion
    [theme.breakpoints.down('sm')]: {
```

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.up('sm')]: {
```suggestion
    [theme.breakpoints.up('md')]: {
```

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.down('xs')]: {
```suggestion
    [theme.breakpoints.down('sm')]: {
```

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.down('xs')]: {
```suggestion
    [theme.breakpoints.down('sm')]: {
```

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.down('xs')]: {
```suggestion
    [theme.breakpoints.down('sm')]: {
```

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.down('xs')]: {
```suggestion
    [theme.breakpoints.down('sm')]: {
```

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +  info: IconProps[];
Disse trenger ikke å være required

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/MessageGDPR.tsx
>      '@media only screen and (max-width: 700px)': {
Bruk theme.breakpoints

2020-10-07 12:52 UTC, olros commented on src/components/miscellaneous/ThemeSettings.tsx
> +// import GA from '../../analytics';
Fjern kommentarer

2020-10-08 16:05 UTC, maxschau commented on src/components/miscellaneous/Emoji.tsx
> +    <span aria-hidden={label ? 'false' : 'true'} aria-label={label ? label : ''} className='emoji' role='img' style={{ color: 'black' }}>
Fort det ja :))

2020-10-08 16:31 UTC, maxschau commented on src/components/miscellaneous/DropdownButton.tsx
> +          <Button onClick={options[selectedIndex].func} ref={anchorRef} type='submit'>
Gud vet. Fikk noe jævlige feilmeldinger av typescript, men viste seg at jeg kun hadde feil type på anchorRef. Fikset nå :)

2020-10-11 12:56 UTC, olros requested changes

2020-10-11 12:56 UTC, olros commented on src/components/miscellaneous/MessageGDPR.tsx
> +      lexDirection: 'column',
Her forsvant det en "f" :)

2020-10-11 12:56 UTC, olros commented on src/components/miscellaneous/Emoji.tsx
> +    <span aria-hidden={'false'} aria-label={label} className='emoji' role='img' style={{ color: 'black' }}>
`aria-hidden="false"` er default så det trengs ikke

2020-10-11 12:56 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
>  import TIHLDELOGO from '../../assets/img/TihldeBackgroundNew.png';
Husk denne

2020-10-11 12:56 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.up('sm')]: {
Husk denne

2020-10-11 12:56 UTC, olros commented on src/components/miscellaneous/ListItem.tsx
> +    [theme.breakpoints.down('xs')]: {
Husk denne

2020-10-11 12:56 UTC, olros commented on src/components/miscellaneous/ThemeSettings.tsx
> +    [theme.breakpoints.down('sm')]: {
```suggestion
    [theme.breakpoints.down('xs')]: {
```

2020-10-11 13:12 UTC, maxschau commented on src/components/miscellaneous/ThemeSettings.tsx
> +    [theme.breakpoints.down('sm')]: {
Hva mener du med husk denne?

2020-10-11 15:11 UTC, olros commented on src/components/miscellaneous/ThemeSettings.tsx
> +    [theme.breakpoints.down('sm')]: {
Prøvde å kommentere på en change request fra forrige gang som ikke var fikset, men ser nå at det ikke var så lett å se 😅

2020-10-11 17:23 UTC, maxschau commented on src/components/miscellaneous/ThemeSettings.tsx
> +    [theme.breakpoints.down('sm')]: {
hæææ

2020-10-11 19:23 UTC, olros commented on src/components/miscellaneous/ThemeSettings.tsx
> +    [theme.breakpoints.down('sm')]: {
La inn flere kommentarer på første review som ikke ble gjort noe med, så da kommenterte jeg på de samme kommentarene med "Husk denne" for at du skulle se de opprinnelige kommentarene

2020-10-12 16:59 UTC, olros commented on src/components/miscellaneous/MessageGDPR.tsx
> +  const [displayState, setDisplayState] = useState<boolean>(true);
```suggestion
  const [displayState, setDisplayState] = useState<boolean>(cookieValue);
```

2020-10-12 17:01 UTC, olros approved these changes

2020-10-12 17:02 UTC, merged