feat(badges): added badges to profile
tihlde/Kvark pull request #263
Opened 2020-10-12 16:51 UTC by SveinJH

![Lint, test and build](https://github.com/tihlde/Kvark/workflows/Lint,%20test%20and%20build/badge.svg)
## Description

Comments/issues/screenshots:
closes #224

![image](https://user-images.githubusercontent.com/43957538/95771722-d1033c80-0cbb-11eb-9454-886655777128.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes

## Typescript convert checklist

- [ ] All relative imports has been converted to absolute imports
- [ ] All HOC's have been replaced with Hooks
- [ ] Uses theme.spacing() instead of custom padding
- [ ] Uses theme.breakpoints instead of custom media queries

2020-10-12 17:04 UTC, maxschau commented on src/containers/Profile/components/ProfileBadges.js
> +          Du har ingen badges enda
<img width="995" alt="image" src="https://user-images.githubusercontent.com/49594236/95772924-ccd81e80-0cbd-11eb-8ebe-0bd6cf221794.png">

Det er ikke mulig å se teksten når man er i DarkMode

2020-10-12 17:15 UTC, maxschau commented on src/containers/Profile/components/ProfileBadges.js
> +const BadgeItem = (props) => {
Props er ubrukt så den behøver ikke være med

2020-10-12 17:24 UTC, maxschau commented on src/containers/Profile/components/ProfileBadges.js
> +    <Grid item xs={6}>
Hvis vi setter denne som xs={12} sm={6} vil den se mye bedre ut på mobil ettersom hver Badge Item vil ta opp 12 kolonner på små skjermer, men 6 på større.

2020-10-12 17:25 UTC, SveinJH commented on src/containers/Profile/components/ProfileBadges.js
> +    <Grid item xs={6}>
Zaim viste meg det akkurat, men sm ga fortsatt litt småfeil, men md={6} var nice

2020-10-12 17:33 UTC, maxschau commented
Synes det så skikkelig bra ut btw 👍

2020-10-13 04:49 UTC, maxschau commented on src/containers/Profile/components/ProfileBadges.js
> +    padding: '18px 6px',
Husk å gjøre om til theme.spacing(theme.spacing(2, 1)
![image](https://user-images.githubusercontent.com/49594236/95816740-1a857300-0d20-11eb-989c-77aab2f7c856.png)

2020-10-19 15:33 UTC, olros requested changes

2020-10-19 15:33 UTC, olros commented on src/containers/Profile/components/ProfileBadges.js
> +      {!badges && (
Du kan bruke ` : ` mellom de to ternary'ene

2020-10-19 17:47 UTC, olros approved these changes
Sjekk at det funker mot api'et som skal være oppdatert med badges nå, så er det bare å squashe og merge 💯

2020-10-19 19:19 UTC, merged