Feat(form-templates): Implementing form templates
TIHLDE/Kvark pull request #275
Opened 2021-11-04 12:52 UTC by MartinClementz

## Description

Legger til muligheten for å bruke en ferdiglaget mal for å oprette spørre- og evaluering-skjemaer.

closes #194 

Changes:
Måtte implementere en liten "hack" for å fjerne all ID fra formtemplates, ettersom det nye skjemaet må ha sine egne unike IDer. 

Screenshots:
<img width="1021" alt="Skjermbilde 2021-11-04 kl  13 48 18" src="https://user-images.githubusercontent.com/26656069/140316217-2398ad77-feb7-4e89-8a42-721d1c371f4b.png">

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes
- [ ] Added Google Analytics tracking if relevant
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2021-11-04 12:59 UTC, MartinClementz commented
Skal legge til muligheten for å opprette sine egne skjemaer også, men vil få litt inputt på hva jeg har gjort så langt :)

For eksempel om "hacken" jeg lagde for å fjerne all ID er noe som er OK å bruke. Er designet var i nærheten av hva du tenkte @olros ?

2021-11-04 15:00 UTC, olros requested changes
Herlig! Akkurat slik jeg tenkte at de kunne ligge ja! Har litt kommentarer på styling og litt småplukk men er strålende totalt sett 😄 

Regner med du har en plan for å kunne markere et form som template også?

2021-11-16 18:52 UTC, olros commented
Noe sånt kan funke for å fjerne id spesifikt med typescript

```typescript
type Option = {
    id: string;
    title: string;
};

type CreateOption = Omit<Field, 'id'>;

type Field = {
    id: string;
    title: string;
    required: boolean;
    options: Array<Option>;
};

type CreateField = Omit<Field, 'id' | 'option'> & { options: Array<CreateOption> };

type Form = {
    id: string;
    title: string;
    fields: Array<Field>;
};

type CreateForm = Omit<Form, 'id' | 'fields'> & { fields: Array<CreateField> };


const removeIdsFromForm = (form: Form): CreateForm => {
    const { id, ...restForm } = form;

    const newFields: Array<CreateField> = [];

    form.fields.forEach((field) => {
        const { id, ...restField } = field;
        const newOptions: Array<CreateOption> = [];

        field.options.forEach((option) => {
            const { id, ...restOption } = option;
            newOptions.push(restOption as CreateOption);
        })

        newFields.push({...restField, options: newOptions } as CreateField);
    });
  
    return { ...restForm, fields: newFields } as CreateForm;
};

```

2021-11-16 19:02 UTC, callumgran requested changes
Ser veldig bra ut, fiks kommentaren til Olaf og fjern kommentarer så er det good.

2021-11-16 19:02 UTC, callumgran commented on src/components/forms/FormEditor.tsx
> +      title: templateTitle, // her kommer det en popup der man kan skrive inn navnet til templaten
Fjern kommentar i ferdig produkt

2021-11-16 19:02 UTC, callumgran commented on src/pages/EventAdministration/components/EventFormEditor.tsx
> +  // fjerner all id fra templaten for å gjøre det sjemaet unikt
Fjern kommentar i ferdig produkt

2021-11-16 19:13 UTC, olros requested changes

2021-11-16 19:13 UTC, olros commented on src/components/forms/FormEditor.tsx
> +      title: templateTitle, // her kommer det en popup der man kan skrive inn navnet til templaten
```suggestion
      title: templateTitle,
```

Det er ikke nødvendig med kommentar her

2021-11-16 19:13 UTC, olros commented on src/components/forms/FormEditor.tsx
> +    setFormDialogOpen(false);
```suggestion
    createForm.mutate(newForm, {
      onSuccess: (data) => {
        showSnackbar(data.title + ' malen ble lagret', 'success');
        setFormDialogOpen(false);
      },
      onError: (e) => {
        showSnackbar(e.detail, 'error');
      },
    });
```

Det er bedre å lukke dialogen kun hvis det går bra. Hvis det går dårlig er det fint å la dialogen bli stående oppe.

2021-11-16 19:13 UTC, olros commented on src/components/forms/FormEditor.tsx
>        </Dialog>
Du må gjerne endre dette til VerifyDialog :)

2021-11-16 19:13 UTC, olros commented on src/hooks/Form.tsx
> +export const useDeleteFormTemplate = (formId: string): UseMutationResult<RequestResponse, RequestResponse, undefined, unknown> => {
Trengs det en egen hook for dette eller er det mulig å gjenbruke den eksisterende `useDeleteForm`

2021-11-16 19:13 UTC, olros commented on src/pages/EventAdministration/components/EventFormEditor.tsx
> +export type delteFormButtonType = {
```suggestion
export type DeleteFormButtonType = {
```

Liten skrivefeil og alltid stor bokstav på typer

2021-11-16 19:13 UTC, olros commented on src/pages/EventAdministration/components/EventFormEditor.tsx
> +  // fjerner all id fra templaten for å gjøre det sjemaet unikt
Du trenger ikke kommentar

2021-11-16 19:13 UTC, olros commented on src/pages/EventAdministration/components/EventFormEditor.tsx
> +        <Button fullWidth onClick={() => onCreateFormFromTemplate()} variant='outlined'>
```suggestion
        <Button fullWidth onClick={onCreateFormFromTemplate} variant='outlined'>
```

2022-01-07 12:20 UTC, closed without merging

2022-01-07 12:21 UTC, MartinClementz commented
Se #323