refactor(profile): refactor profile to typescript
tihlde/Kvark pull request #311
Opened 2020-11-14 18:35 UTC by SveinJH

![Lint, test and build](https://github.com/tihlde/Kvark/workflows/Lint,%20test%20and%20build/badge.svg)
## Description

Comments/issues/screenshots:
Form i ProfileSettings må fortsatt refaktoreres til react-hook-form, gjorde ikke dette i denne PR-en, da det er et stykke unda...
closes #310

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes

## Typescript convert checklist

- [ ] All relative imports has been converted to absolute imports
- [x] All HOC's have been replaced with Hooks
- [x] Uses theme.spacing() instead of custom padding
- [x] Uses theme.breakpoints instead of custom media queries

2020-11-14 19:42 UTC, olros requested changes
Mye bra! Ta en gjennomgang i alle filene at stylingen er oppdatert med `theme.spacing`, `theme.breakpoints` og at **alle** imports er absolutte 🦸‍♂️

2020-11-14 19:42 UTC, olros commented on src/components/inputs/TextField.tsx
> +  control: any;
Ta en titt her: https://react-hook-form.com/ts, så kan du fjerne `any`

2020-11-14 19:42 UTC, olros commented on src/components/inputs/TextField.tsx
> +  required = undefined,
Hvorfor er denne undefined og ikke false?

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfileEvents.tsx
>        )}
`events.length < 1` på linje 62 kan endres til `!events.length`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfileEvents.tsx
>              );
```jsx
{events &&
  events.map((event) => {
    if (!event.expired) {
      return (
        <ListItem
          expired={event.expired}
          img={event.image}
          imgAlt={event.image_alt}
          info={[
            { label: getFormattedDate(moment(event.start_date, ['YYYY-MM-DD HH:mm'], 'nb')), icon: DateIcon },
            { label: event.location, icon: LocationIcon },
          ]}
          key={event.id}
          link={URLS.events + ''.concat(`${event.id}`, '/')}
          title={event.title}
        />
      );
    }
    return '';
  })}
```

Kan kortes ned til:

```jsx
{events?.map((event) => !event.expired ?
  (
    <ListItem
      expired={event.expired}
      img={event.image}
      imgAlt={event.image_alt}
      info={[
        { label: getFormattedDate(moment(event.start_date, ['YYYY-MM-DD HH:mm'], 'nb')), icon: DateIcon },
        { label: event.location, icon: LocationIcon },
      ]}
      key={event.id}
      link={`${URLS.events}${event.id}/`)}
      title={event.title}
    />
  ) : (<></>)
)};
```

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfileNotifications.tsx
>      alignItems: 'center',
Padding og margin på linjene under må byttes ut med `theme.spacing`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfileNotifications.tsx
>    let elementClass = classes.message;
Flytt `elementClass` inn i `<Paper className={...} >`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfileNotifications.tsx
>        ) : notifications.length > 0 ? (
`notifications.length > 0` === `notifications.length`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfileNotifications.tsx
> +        notifications.map((notification, i) => <NotificationItem key={i} notification={notification} />)
Det er best om key kan finnes naturlig fra det vi mapper, i dette tilfellet `notification.id`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfilePaper.tsx
>  import ProfileBadges from './ProfileBadges';
Bruk absolutt import

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfilePaper.tsx
> +}));
Alt av padding, margin, osv her må bruke `theme.spacing`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfilePaper.tsx
> +  const notificationsTab = { label: 'Varsler', icon: NotificationsIcon, badge: userData && userData.unread_notifications };
Bruk optional chaining: `userData && userData.unread_notifications` = `userData?.unread_notifications`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfilePaper.tsx
> +    iconEnd?: any;
Unngå `any`. Se hvordan du kan type komponenter som blir sendt som props i EventRegistration.tsx, linje 49-62

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfilePaper.tsx
> +        {userData && userData.first_name ? (
Optional chaining

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfilePaper.tsx
> +            <ProfileNotifications isLoading={isLoading} notifications={userData ? userData.notifications : []} />
`userData ? userData.notifications : []` == `userData?.notifications || []`

2020-11-14 19:42 UTC, olros commented on src/containers/Profile/components/ProfileSettings.tsx
> +              onChange={(e) => setUserData({ ...userData, cell: parseInt(e.target.value) })}
Bruk `Number()` istedenfor `parseInt()`. Endre alle steder i filen

2020-11-14 19:42 UTC, olros commented on src/types/Types.tsx
> +}
Badge inneholder også `image_alt: string` og `id: string`. Image og image_alt kan være null

2020-11-14 19:53 UTC, SveinJH commented on src/components/inputs/TextField.tsx
> +  required = undefined,
Er Zaim sine inputs, så ikke sikker 😂

2020-11-14 19:57 UTC, SveinJH commented on src/components/inputs/TextField.tsx
> +  required = undefined,
![image](https://user-images.githubusercontent.com/43957538/99155850-02f12f80-26bc-11eb-988e-e618d19f01bb.png)
Derfor regner jeg med...

2020-11-14 20:14 UTC, SveinJH commented on src/containers/Profile/components/ProfilePaper.tsx
> +    iconEnd?: any;
![image](https://user-images.githubusercontent.com/43957538/99156062-48aef780-26be-11eb-8b36-12ddfbfaa04a.png)

Får denne når jeg setter icon til `React.ComponentType<{ className: string }>;`

2020-11-16 15:48 UTC, olros commented on src/components/inputs/TextField.tsx
> +  required = undefined,
Okei, zaim forklarte det og det gir mening

2020-11-16 20:35 UTC, olros requested changes

2020-11-16 20:35 UTC, olros commented on src/containers/Profile/components/ProfileEvents.tsx
> +        !event.expired ? (
Sorry, men du kan faktisk bruke && istedenfor ? og da slippe å returnere <></> hvis ikke. Hehe

2020-11-16 20:35 UTC, olros commented on src/containers/Profile/components/ProfilePaper.tsx
> +          <Icon className={className ? className : ''} color={tab === label ? 'primary' : 'inherit'} />
className || ''

2020-11-16 20:35 UTC, olros commented on src/containers/Profile/index.tsx
> +    top: theme.spacing(-8),
Akkurat top kan være -60 siden det så tett knyttet opp mot hvor stor diven over er

2020-11-16 20:41 UTC, SveinJH commented on src/containers/Profile/index.tsx
> +    top: theme.spacing(-8),
hahah enda flere theme.spacings... trodde jeg tok alle denne gangen... mb

2020-11-21 12:14 UTC, Zenjjim commented on src/components/inputs/TextField.tsx
> +  required = undefined,
Denne kan godt renames til `requiredErrorMessage`

2020-11-21 12:14 UTC, Zenjjim commented on src/containers/Profile/components/ProfileBadges.tsx
> +            <strong>{badge.title}</strong>
jeg husker ikke om dette fungere for bold. Men MUI har [text-theme system](https://material-ui.com/system/typography/)

2020-11-21 12:14 UTC, Zenjjim commented on src/containers/Profile/components/ProfileNotifications.tsx
>    let elementClass = classes.message;
unngå bruken av `let`,  bruk `const `

2021-01-18 17:10 UTC, olros approved these changes
🥇

2021-01-18 17:11 UTC, merged