feat(gallery): implementing basic digitalt photo gallery
TIHLDE/Kvark pull request #317
Opened 2021-12-21 13:22 UTC by callumgran

## Description
Skriver mer utfyldende senere, må factory resette pcen så må bare få lasta opp koden.
closes #

Changes:

Screenshots:

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes
- [ ] Added Google Analytics tracking if relevant
- [ ] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2022-03-04 08:34 UTC, olros requested changes
Sett på til og med ImageGrid, vi kan parprogrammere neste uke for å komme gjennom alt 😉 Utseende-messig ser det veldig fint ut, vi må bare rydde opp litt

2022-03-04 08:34 UTC, olros commented on src/AppRoutes.tsx
> +import GalleryDetails from 'pages/GalleryDetails';
```suggestion
const Gallery = lazy(() => import(/* webpackChunkName: "gallery" */ 'pages/Gallery'));
const GalleryDetails = lazy(() => import(/* webpackChunkName: "gallery_details" */ 'pages/GalleryDetails'));
```

Disse kan importeres lazily ettersom de ikke brukes hver gang brukeren besøker siden

2022-03-04 08:34 UTC, olros commented on src/URLS.tsx
> +  gallery: '/albumer/',
```suggestion
  gallery: '/album/',
```

Flertall av album er også album
*Ett album, flere album*

Kan også vurdere å heller bruke `/galleri/` som url, hva tenker du?

2022-03-04 08:34 UTC, olros commented on src/api/api.tsx
> +  PictureRequired,
Fjern ubrukt import

2022-03-04 08:34 UTC, olros commented on src/api/api.tsx
> +  deleteAlbum: (albumSlug: string) => IFetch<RequestResponse>({ method: 'DELETE', url: `${GALLERY_ENDPOINT}/${albumSlug}/` }),
Bruk gallery gjennomgående, ikke album noen steder og gallery andre steder

2022-03-04 08:34 UTC, olros commented on src/components/miscellaneous/AspectRatioImg.tsx
> -const AspectRatioImg = ({ alt, borderRadius, className, ratio = 21 / 9, src, sx }: AspectRatioImgProps) => {
Ikke fjern dette, hvis du ikke ønsker en aspectRatio på bildet så trenger du heller ikke bruke denne komponenten. Revert også alle stedene der du har lagt til `ratio={21 / 9}`

2022-03-04 08:34 UTC, olros commented on src/components/miscellaneous/GalleryListItem.tsx
> +// Project components
Fjern kommentarer

2022-03-04 08:34 UTC, olros commented on src/hooks/Gallery.tsx
> +};
```suggestion
export const useGalleryById = (gallerySlug: string) => useQuery<Gallery, RequestResponse>([GALLERY_QUERY_KEY, albumSlug], () => API.getGallery(gallerySlug));
```

2022-03-04 08:34 UTC, olros commented on src/hooks/Gallery.tsx
> +export const useDeleteAlbum = (albumSlug: string): UseMutationResult<RequestResponse, RequestResponse, unknown, unknown> => {
Endre navn til gallery

2022-03-04 08:34 UTC, olros commented on src/hooks/Gallery.tsx
> +    },
```suggestion
    onSuccess: () => queryClient.invalidateQueries(GALLERY_QUERY_KEY),
```

2022-03-04 08:34 UTC, olros commented on src/hooks/Gallery.tsx
> +  return useQuery<Picture, RequestResponse>([GALLERY_QUERY_KEY, PICTURE_QUERY_KEY, id, albumSlug], () => API.getPicture(albumSlug, id));
Bruk samme rekkefølge på cache keys gjennomgående
```suggestion
  return useQuery<Picture, RequestResponse>([GALLERY_QUERY_KEY, albumSlug, PICTURE_QUERY_KEY, id], () => API.getPicture(albumSlug, id));
```

2022-03-04 08:34 UTC, olros commented on src/hooks/Gallery.tsx
> +    },
Det holder å overskrive
```suggestion
    onSuccess: (data) => queryClient.setQueryData([GALLERY_QUERY_KEY, albumSlug, PICTURE_QUERY_KEY, id], data),
```

2022-03-04 08:34 UTC, olros commented on src/hooks/Gallery.tsx
> +    },
```suggestion
    onSuccess: () => queryClient.invalidateQueries([GALLERY_QUERY_KEY, albumSlug]),
```

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +import { Box, Button, MenuItem } from '@mui/material';
Fjern ubrukt MenuItem-import

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +import { useEvents } from 'hooks/Event';
Ubrukt import

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +import Select from 'components/inputs/Select';
Ubrukt import

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +  const { handleSubmit, register, watch, formState, setValue, control } = useForm<FormValues>();
```suggestion
  const { handleSubmit, register, watch, formState, setValue } = useForm<FormValues>();
```

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +  // const events = useMemo(() => (data ? data.pages.map((page) => page.results).flat() : []), [data]);
Fjern kommentar

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +        )} */}
Fjern

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +        <SubmitButton className={classes.margin} formState={formState}>
```suggestion
        <SubmitButton sx={{ mt: 2 }} formState={formState}>
```

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +        </Button>
Trengs det en hel dialog for å vise frem tillatte filtyper? I ImageUpload er det allerede en restriction på hvilke filer som kan velges så jeg mener at du kan fjerne knapp og dialog helt

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +      },
Dialogen for opprettelse av album bør lukkes ved opprettelse, eller man bør redirigeres til det nyopprettede albumet
```suggestion
      onSuccess: (data) => {
        showSnackbar('Albumet ble lagt til', 'success');
        closeDialog();
        // eller:
        navigate(`${URLS.gallery}${data.id}/`)
      },
```

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +      image_alt: data.image_alt,
Når du allerede har brukt `...data` så trenger du ikke linje 41-44 i tillegg

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/components/CreateGallery.tsx
> +      <Dialog onClose={() => setOpen(false)} open={open} titleText={'Opprett et nytt bilde album'}>
```suggestion
      <Dialog onClose={() => setOpen(false)} open={open} titleText='Opprett nytt album'>
```

2022-03-04 08:34 UTC, olros commented on src/pages/Gallery/index.tsx
> +// Types
Fjern kommentarer

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/GalleryEditor.tsx
> +    await editGallery.mutate(Album, {
```suggestion
    await editGallery.mutate(data, {
```

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/GalleryEditor.tsx
> +      },
Send bruker til galleri-forsiden ved sletting av galleri
```suggestion
      onSuccess: () => {
        showSnackbar('Albumet ble slettet', 'success');
        navigate(URLS.galleries)
      },
```

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/GalleryEditor.tsx
> +        <input hidden value={data?.image} {...register('image')} />
Du trenger ikke denne, hent heller `data.image` ved update i mutate

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/GalleryRenderer.tsx
> +// Components
FJern kommentarer

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/GalleryRenderer.tsx
> +import ImageGrid from './ImageGrid';
Bruk absolutt imports

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/GalleryRenderer.tsx
> +type GalleryRendererProps = {
```suggestion
export type GalleryRendererProps = {
```

Eksporter props når komponenten også eksporteres

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/GalleryRenderer.tsx
> +  data: Gallery;
```suggestion
  gallery: Gallery;
```

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/ImageDialog.tsx
> +import PictureEditorDialog from './PictureEditor';
Absolutt import

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/ImageDialog.tsx
> +};
Trenger du en egen komponent for dette? Legg det heller rett inn der den brukes. `fontSize=100%` ser også litt rart ut.

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/ImageGrid.tsx
> +};
```suggestion
export const ImageGridLoading = () => (
    <ImageList cols={3} gap={8} variant='masonry'>
      <ImageListItem>
        <img loading='lazy' />
      </ImageListItem>
    </ImageList>
  );
```

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/ImageGrid.tsx
> +type ImageGridProps = {
```suggestion
export type ImageGridProps = {
```

2022-03-04 08:34 UTC, olros commented on src/pages/GalleryDetails/components/ImageGrid.tsx
> +  };
Dette ser ikke bra ut. Array'en du sender til setSelectedImg er ikke typet i det hele tatt. Vil være mye bedre å sende inn et objekt av Picture og setOpenPicture kan kalkuleres ut fra om SelectedImg er null eller ikke

2022-03-13 14:25 UTC, callumgran reviewed
Har oppdatert alt etter de tilbakemeldingene du har gitt, fiksa gjennomgående kontinuitetsfeil og tuklet med ting som ikke funket helt optimalt (sletting og editing).

2022-03-14 07:48 UTC, olros approved these changes
Ser flott ut! Du har gjort en flott jobb 🚀 Fint at du endelig kan starte på noe annet

2022-03-14 07:54 UTC, merged