feat(stories): view list of events in a new way
tihlde/Kvark pull request #322
Opened 2020-11-26 18:15 UTC by olros

![Lint, test and build](https://github.com/tihlde/Kvark/workflows/Lint,%20test%20and%20build/badge.svg)
## Description

Comments/issues/screenshots:
![image](https://user-images.githubusercontent.com/31009729/100382428-9e1ec900-301b-11eb-8e33-dbaaad11adc6.png)
![image](https://user-images.githubusercontent.com/31009729/100382441-a7a83100-301b-11eb-95f9-23e599eadbd4.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes

## Typescript convert checklist

- [ ] All relative imports has been converted to absolute imports
- [ ] All HOC's have been replaced with Hooks
- [ ] Uses theme.spacing() instead of custom padding
- [ ] Uses theme.breakpoints instead of custom media queries

2021-01-06 13:46 UTC, Zenjjim requested changes

2021-01-06 13:46 UTC, Zenjjim commented on src/api/hooks/User.tsx
> +      .then((user) => !subscribed || setHavePermission(Boolean(user?.groups.some((group) => groups.includes(group)))))
Den er vel en Bool fra før av? Du trenger vel ikke spesifisere det

2021-01-06 13:46 UTC, Zenjjim commented on src/api/hooks/User.tsx
> +      .then((user) => !subscribed || setHavePermission(Boolean(user?.groups.some((group) => groups.includes(group)))))
mtp trye/false/undefined=false

2021-01-06 13:46 UTC, Zenjjim commented on src/components/story/StoryPopup.tsx
> +          <div>
bruk <> der du ikke bruker classer som wrapper

2021-01-06 13:46 UTC, Zenjjim commented on src/components/story/StoryPopup.tsx
> +          <div>
fjerner unødvendig tags fra html map

2021-01-06 13:46 UTC, Zenjjim commented on src/components/story/StoryPopup.tsx
> +    <Dialog classes={{ paper: classes.paper }} fullScreen={fullScreen} fullWidth maxWidth='md' onClose={onClose} open={open} style={{ zIndex: 20000 }}>
haha this z-index tho

2021-01-06 13:46 UTC, Zenjjim commented on src/containers/NewLanding/components/CalendarListView.js
> +import Story from '../../../components/story/Story';
absolute imports

2021-01-06 13:46 UTC, Zenjjim commented on src/containers/Events/index.js
> +import Story from '../../components/story/Story';
abs imports

2021-01-06 13:46 UTC, Zenjjim commented on src/containers/Events/index.js
> +import Story from '../../components/story/Story';
kommer vel ved refactor kanskje 🤔

2021-01-06 13:46 UTC, Zenjjim commented on src/components/story/StoryPopup.tsx
> +        setTimeout(() => scrollToIndex(index, smooth), 100);
lag 100 som en variabel. Skjønner ikke hva den betyr. Mest sannsylig ms animation men greit å ha som en variabel for enkel forståelse

2021-01-06 15:15 UTC, olros commented on src/api/hooks/User.tsx
> +      .then((user) => !subscribed || setHavePermission(Boolean(user?.groups.some((group) => groups.includes(group)))))
User kan være null og da vil vi fremdeles at det skal bli false og ikke null

2021-01-06 15:16 UTC, olros commented on src/containers/NewLanding/components/CalendarListView.js
> +import Story from '../../../components/story/Story';
Dette er en js fil

2021-01-06 15:16 UTC, olros commented on src/containers/Events/index.js
> +import Story from '../../components/story/Story';
Js fil, men ja ligger i refaktor

2021-01-12 10:24 UTC, olros commented on src/components/story/StoryPopup.tsx
> +          <div>
Må til siden `classes.bottom` er en grid og tekst-elementene skal ligge over hverandre i y-retning mens grid'en går i x-retning

2021-01-14 10:42 UTC, Her0elt approved these changes
looks good

2021-01-14 11:09 UTC, merged