feat/formtemplates
TIHLDE/Kvark pull request #323
Opened 2022-01-07 12:20 UTC by MartinClementz

## Description
Nå kan man bruke ferdiglagde maler som utgangspunkt når man skal opprette skjemaer. Dette gjør det lettere for de som oppretter arrangementer å lage spørreskjemaer kjapt.
 
* Kan bruke ferdiglagde maler for å opprette skjemaer.
* Kan lagre maler slik at de kan brukes senere.

Denne følger #275 der denne funksjonen ble jobbet på. Ganske mye hadde endret seg siden den ble jobbet på, så fant det lettest å bare lage en ny pull request. 

**En ting jeg er usikker på er om endringen jeg gjorde i typen `TextFormField` ødelegger noe annet.** Endringen ble gjort for å hindre typescript error i begge RemoveIds funksjonene, der det ikke går an å hente ut en `id` fra type `unknown[]`

closes #194

Changes:
* Endrer formhooks
* Legger til og endrer noen typer

Screenshots:
<img width="1027" alt="Skjermbilde 2022-01-07 kl  12 57 04" src="https://user-images.githubusercontent.com/26656069/148541202-2cf0410f-2fb8-40f9-bc3e-0cf8e5639b63.png">
<img width="1046" alt="Skjermbilde 2022-01-07 kl  12 57 13" src="https://user-images.githubusercontent.com/26656069/148541204-764a5c34-b779-4791-8de2-6117815967bf.png">
<img width="997" alt="Skjermbilde 2022-01-07 kl  12 57 49" src="https://user-images.githubusercontent.com/26656069/148541206-ed2a6d2c-99d3-45d7-ba32-58cb7766ee61.png">
<img width="993" alt="Skjermbilde 2022-01-07 kl  12 59 10" src="https://user-images.githubusercontent.com/26656069/148541210-de5ae1cb-9327-483f-a8ce-ea66d269407b.png">
<img width="759" alt="Skjermbilde 2022-01-07 kl  12 59 16" src="https://user-images.githubusercontent.com/26656069/148541211-22199be5-97e6-4ea4-997a-e8bd3ace2a1c.png">

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes
- [x] Added Google Analytics tracking if relevant
- [x] Pull request title follows [conventional commits](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) (`type(scope): description`)
- [x] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2022-01-09 10:26 UTC, olros requested changes
Herlig jobbet! Det funker veldig fint. Har allikevel et forslag til en liten omstrukturering ift hvor det ligger på nettsiden:

Jeg hadde egentlig tenkt at vi bare skulle markere eksisterende skjemaer som ble brukt på arrangementer med `template: true`. Å lage helt nye skjemaer slik som du har gjort var veldig lurt siden vi da kan redigere dem uten å tenke på å ødelegge for et arrangement. Men det tillatter oss også å ha hele flyten med opprettelse av maler i listen over maler som kan velges:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/31009729/148678224-526d6553-046a-4818-bd79-532c1f0b8007.png">

Da kan vi også gjøre det mulig å redigere maler som er opprettet direkte fra listen over maler:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/31009729/148678289-849b8961-2e41-4541-b258-070664d5ea1e.png">

Da kan vi fjerne `Lagre som mal`-knappen i bunnen av hvert skjema og håndtere alt av maler på kun et sted (Opprette, endre, slette, velge og bruke).

Tanker om det? Kan utdype hvis noe var uklart. Evt så kan vi ta det på første møte.

2022-01-09 10:26 UTC, olros commented on src/components/forms/FormFieldsEditor.tsx
> +          contentText='Hvis du lagrer som mal vil du kunne bruke malen til å opprette skjemaer senere. Gi malen en passende tittel.'
```suggestion
          contentText='Når du lager en mal så kan du enkelt bruke feltene i dette skjemaet i andre skjemaer senere. Gi malen en passende tittel.'
```

2022-01-09 10:26 UTC, olros commented on src/components/forms/FormFieldsEditor.tsx
> +              size='small'
Tenger kanskje ikke være `small`?

2022-01-09 10:26 UTC, olros commented on src/components/forms/FormFieldsEditor.tsx
> +          onConfirm={() => saveAsTemplate()}
```suggestion
          onConfirm={saveAsTemplate}
```

2022-01-09 10:26 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +    <>
Du kan fjerne `<>` som er rundt <Expand />

2022-01-09 12:57 UTC, MartinClementz commented
Likte veldig godt ideen med å kunne _"opprette, endre, slette, velge og bruke"_ malene på ett sted. Det kan fikses. 

Men jeg tenker det kan være lurt å kunne opprette maler direkte fra hver skjema-redigerings-visning. Hvis arrangørene for eksempel har laget et fint skjema tidligere, så kan de selv gjøre det om til en mal isteden for å lage det helt på nytt. I tillegg gir det arrangørene muligheten til å ombestemme seg, slik at hvis de ble fornøyde med spørreskjemaet midt i prossessen så kan de lagre det som en mal. Dette matcher også opp med den originale tanken om å kunne sette hver skjema med `template: true`

2022-01-09 13:02 UTC, MartinClementz commented on src/components/forms/FormFieldsEditor.tsx
> +    const { id, ...restField } = field;
hmm.. prøvde dette, men jeg fikk en ESLint error istedet. Fikset det med å sette gjøre

```JavaScript
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const { id, ...restField } = field; // eslint-disable-line
```

2022-01-09 13:06 UTC, olros commented
> Men jeg tenker det kan være lurt å kunne opprette maler direkte fra hver skjema-redigerings-visning. Hvis arrangørene for eksempel har laget et fint skjema tidligere, så kan de selv gjøre det om til en mal isteden for å lage det helt på nytt. I tillegg gir det arrangørene muligheten til å ombestemme seg, slik at hvis de ble fornøyde med spørreskjemaet midt i prossessen så kan de lagre det som en mal. Dette matcher også opp med den originale tanken om å kunne sette hver skjema med `template: true`

Kan være enig i det. Mitt forslag er da at "Lagre som mal"-knappen legges under skjema-innstillinger slik at selve redigeringen av spørsmål kan være uavhengig og brukes andre steder, mens det blir hele skjemaet som lagres som mal:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/31009729/148683335-5ca0371a-b937-4e57-9ccd-c59e56e85b0e.png">

2022-01-09 13:27 UTC, olros commented on src/components/forms/FormFieldsEditor.tsx
> +    const { id, ...restField } = field;
Ahh, det er kanskje bare eslint-feil ja. Prøv å fjerne
```es6
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
```

2022-01-20 17:23 UTC, MartinClementz commented
Det er ikke lagt til en "ny mal" knapp under visningen av alle malene, ellers er alle de andre endringene implementert. Det er mulig å lage nye maler gjennom spørreskjema, der man kan trykke "lagre som mal". 

Tenker å lage en issue på "ny mal" knappen, så kan jeg eller noen andre legge den til senere.

2022-01-20 21:06 UTC, olros requested changes
Meget godt jobbet, blir sjukt nice å få dette inn 🚀

2022-01-20 21:06 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +const removeIdsFromForm = (form: Form): FormCreate => {
Flytt denne funksjonen til utils.tsx siden den er helt lik den som brukes i en annen fil lengre oppe.

2022-01-20 21:06 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +              <VerifyDialog color='warning' contentText='Å slette en mal kan ikke reverseres.' onConfirm={onDeleteForm} titleText='Er du sikker?'>
Bør være rød
```suggestion
              <VerifyDialog color='error' contentText='Å slette en mal kan ikke reverseres.' onConfirm={onDeleteForm} titleText='Er du sikker?'>
```

2022-01-20 21:06 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +            <Stack direction={{ xs: 'column', md: 'row' }} spacing={1} sx={{ pb: 1 }}>
```suggestion
            <Stack direction={{ xs: 'column', md: 'row' }} gap={1}>
```

Også `gap={1}` på Stack over

2022-01-20 21:06 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +              {!isLoading && !isError && form ? <FormFieldsEditor form={form} newTitle={formtemplateTitle}></FormFieldsEditor> : ''}
Her kunne du vel bruke onSave?
```suggestion
              {!isLoading && !isError && form && <FormFieldsEditor onSave={() => setIsCreatingTemplate(false)} form={form} newTitle={formtemplateTitle}></FormFieldsEditor>}
```

2022-01-20 21:06 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +              <Button onClick={() => setIsCreatingTemplate(false)} sx={{ mt: 1 }} variant='outlined'>
Og da fjerne dette

2022-01-25 19:30 UTC, MartinClementz commented
Alle endringene som ble pekt på er implementert. Klar for merge, eller er det flere ting som skal endres/legges på?

2022-01-26 06:53 UTC, olros commented
> Alle endringene som ble pekt på er implementert. Klar for merge, eller er det flere ting som skal endres/legges på?

Tar en ny, siste gjennomgang på møtet i morgen. Regner med det er good, men alltid fint men en ny sjekk etter at ting er fikset/endret

2022-01-26 08:46 UTC, olros requested changes
Bare noen småting igjen nå 🔥

2022-01-26 08:46 UTC, olros commented on CHANGELOG.md
> +- ✨ **Skjemamaler**. Administratorer kan nå lage maler som man kan ta utgangspunkt i når man lager et nytt skjema.
Legg det under "Ny versjon" ;)

2022-01-26 08:46 UTC, olros commented on src/components/forms/FormDetailsEditor.tsx
> +const EventFormDetailsEditor = ({ form }: DeafultFormDetailsEditor) => {
```suggestion
type EventFormDetailsEditorProps = {
  form: EventForm | TemplateForm;
};

const EventFormDetailsEditor = ({ form }: EventFormDetailsEditorProps) => {
```

2022-01-26 08:46 UTC, olros commented on src/components/forms/FormFieldsEditor.tsx
> +      { title: formTitle, fields: fields, resource_type: form.resource_type || 'Form' },
Legg heller til `'form'` i resource_type-typen

```suggestion
      { title: formTitle, fields: fields, resource_type: form.resource_type },
```

2022-01-26 08:46 UTC, olros commented on src/hooks/Utils.tsx
> +export const removeIdsFromFields = (fields: Array<TextFormField | SelectFormField>) => {
Dette er ikke en hook så jeg tror den passer bedre i utils.tsx filen i root. Også hadde det vært lurt med JsDoc i tillegg for den:
```
/**
  * Removes id's from fields and the options of the given fields
  * 
  * @param fields The fields to remove the id's from
*/
```

2022-01-26 08:46 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +    };
```suggestion
    const onCreateTemplate = () => createForm.mutate(newFormTemplateCreate, {
        onSuccess: (data) => {
          showSnackbar(`Malen med navn "${data.title} ble opprettet"`, 'success');
          setFormtemplateId(data.id);
          setIsCreatingTemplate(true);
        },
        onError: (e) => showSnackbar(e.detail, 'error'),
      });
```

2022-01-26 08:46 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +          ) : (
Tror dette bør funke
```suggestion
          {isCreatingForm ? (!isLoading && !isError && form && (
                <FormFieldsEditor canEditTitle={true} form={form} onSave={() => setIsCreatingTemplate(false)} />
              )) : (
```

2022-01-26 08:46 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +      title: 'BLANK',
Kan kanskje finne en bedre default tittel? For eks:
```suggestion
      title: 'Ny mal',
```

2022-01-26 08:46 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +    <Expand flat header={formtemplate.title} sx={{ mt: 1 }}>
Dropp marginTop for å unngå mellomrom mellom templates'ene:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/31009729/151131036-c5aad25b-730b-4ada-965c-98729810bc06.png">

```suggestion
    <Expand flat header={formtemplate.title}>
```

2022-01-26 08:46 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +              <Typography variant='body2'>Bruk en ferdiglagd mal som utgangspunkt når du oppretter ett skjema.</Typography>
Så kan vi heller legge til `gutterBottom` for å få margin mellom tekst og templates
```suggestion
              <Typography gutterBottom variant='body2'>Bruk en ferdiglagd mal som utgangspunkt når du oppretter ett skjema.</Typography>
```

2022-02-01 12:09 UTC, martcl commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +          ) : (
Fikk ikke til å skrive det sånn. TS klagde på type error

2022-02-01 14:25 UTC, olros approved these changes
Ser flott ut, fungerer bra og koden er fin. Meget bra jobbet! Veldig deilig feature å få inn 💯 

Se på kommentaren min og sjekk om det var meningen at den skal være med 😉

2022-02-01 14:25 UTC, olros commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +  }, [formtemplate]);
Er det meningen at denne skal være med? Og hvis det hvorfor? `resource_type` kommer vel med fra backend allikevel nå.

2022-02-01 14:55 UTC, martcl commented on src/pages/EventAdministration/components/EventFormAdmin.tsx
> +  }, [formtemplate]);
Var med fra en testing når den ikke gjorde det, hadde vel glemt å fjerne den 🤨

2022-02-01 15:03 UTC, merged