refactor(typescript): landing
tihlde/Kvark pull request #335
Opened 2020-12-15 12:22 UTC by olros

## Description

#243 and #255 

Comments/issues/screenshots:
- Refactored the Landing-page and its components to Typescript
- Change name of landing-folder from "NewLanding" to "Landing"
- Add global overrides for link color to remove the green links, uses the primary color instead
- Update wave with svg's instead of png's to render the waves. This allows to color to be dynamic and are set to equal the background.
- No big visual changes, the waves may look a little bit different

![image](https://user-images.githubusercontent.com/31009729/102214177-2801d980-3ed8-11eb-96c3-14754a8d18c7.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes

## Typescript convert checklist

- [ ] All relative imports has been converted to absolute imports
- [ ] All HOC's have been replaced with Hooks
- [ ] Uses theme.spacing() instead of custom padding
- [ ] Uses theme.breakpoints instead of custom media queries

2020-12-15 13:10 UTC, Zenjjim requested changes
Good joob. A couple of comments about clean code but logic looks good.

2020-12-15 13:10 UTC, Zenjjim commented on src/containers/Landing/components/EventsListView.tsx
> +        {events.map((event, index) => index < 3 && <ListItem event={event} key={event.id} />)}
make "3" a constant with a propper name

2020-12-15 13:10 UTC, Zenjjim commented on src/containers/Landing/components/EventsView.tsx
> +    if (!oldEvents.length && tab === 1) {
make 0 and 1 enums for better readability

2020-12-15 13:10 UTC, Zenjjim commented on src/containers/Landing/components/NewsListView.tsx
> +        <div className={classes.container}>{news.map((newsItem, index) => index < 2 && <ListItem key={index} news={newsItem} />)}</div>
same as above. make 2 a constant with a name

2020-12-15 13:10 UTC, Zenjjim commented on src/containers/Landing/index.tsx
> +import Helmet from 'react-helmet';
is helmet even used?

2020-12-15 13:10 UTC, Zenjjim commented on src/containers/Landing/index.tsx
> +      <div className={classes.smoke}>
would not a smoke component be good since its used almost everywhere?

2020-12-15 13:10 UTC, Zenjjim commented on src/index.tsx
>            <JobPostProvider>
not a part of this PR but index.tsx is getting big. Sould splitt ut ProviderHandler and Router to seprate files

2020-12-15 13:11 UTC, Zenjjim commented
![image](https://user-images.githubusercontent.com/23628986/102219171-664ec700-3edf-11eb-9ddf-30107ad1a8b6.png)
There is a line that should get fixed right below the waves

2020-12-15 13:58 UTC, olros commented on src/index.tsx
>            <JobPostProvider>
I agree

2020-12-15 14:01 UTC, olros commented on src/assets/css/index.css
>  }
Thought I'd leave it as a "backup", but it may not be necessary

2020-12-15 14:04 UTC, olros commented on src/containers/Landing/index.tsx
> +import Helmet from 'react-helmet';
It works quite fine actually:
![image](https://user-images.githubusercontent.com/31009729/102224852-c006bf80-3ee6-11eb-9516-5b3f40729d6d.png)

2020-12-15 14:08 UTC, olros commented on src/containers/Landing/index.tsx
> +      <div className={classes.smoke}>
It's used like this 3 places: Landing, About and Companies. I don't think that is enough to create a new component for it

2021-01-05 16:07 UTC, Zenjjim approved these changes

2021-01-05 18:59 UTC, merged