fefactor(typescript): login and companies
tihlde/Kvark pull request #343
Opened 2021-01-15 20:50 UTC by olros

## Description

Comments/issues/screenshots:
- Made URLS and settings (renames to constant) tsx-files
- Created a container-component which provides the Material-UI container with default props
- Refactor Login and Companies-pages to typescript and move their text from separate files into the component
- Used React-Hook-Form in all forms
- No big visual changes

closes #321 
#243 
#197 

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes

## Typescript convert checklist

- [x] All relative imports has been converted to absolute imports
- [x] All HOC's have been replaced with Hooks
- [x] Uses theme.spacing() instead of custom padding
- [x] Uses theme.breakpoints instead of custom media queries

2021-01-15 21:06 UTC, maxschau commented on src/containers/Companies/components/CompaniesForm.tsx
> +// Material UI Components
:O

2021-01-15 21:09 UTC, maxschau commented on src/containers/Companies/index.tsx
> +          <div className={classes.grid}>
En tanke er å benytte Material UI-grid for å få en mer rød tråd over hele prosjektet. Dette er selvfølgelig ikke kritisk, men en tanke for å få et mer helhetlig og konsistent prosjekt.

2021-01-15 21:10 UTC, maxschau commented on src/containers/Companies/index.tsx
> +          <div className={classes.grid}>
Spesielt siden vi benytter Material-UI-grid flere steder i prosjektet. Dette kan dog gjøres i en egen branch

2021-01-15 21:14 UTC, maxschau commented on src/theme.tsx
> +  const get = <T,>({ light, dark }: { light: T; dark: T }): T => {
Vet ikke helt om det er mulig, men er det mulig å skrive noe annet enn "T" for å øke lesbarheten? Jeg antar at T er theme eller noe slikt , men det er ikke nødvendigvis intuitivt for alle

2021-01-15 21:40 UTC, olros commented on src/theme.tsx
> +  const get = <T,>({ light, dark }: { light: T; dark: T }): T => {
Vel, T er det som er vanlig å bruke i Typescript for generics

2021-01-15 21:42 UTC, olros commented on src/containers/Companies/index.tsx
> +          <div className={classes.grid}>
Tja, kan diskuteres men jeg personlig er lite fan av Material-UI grid. Synes det fungerer dårlig og at det blir mye overflødig kode. I tillegg er det ikke faktisk grid, men flexbox og man får dermed ikke fordelene med CSS Grid.

2021-01-15 21:44 UTC, olros commented on src/components/layout/Container.tsx
> +// Material UI Components
Hahah, åpen for endringer der altså. Har vel egt bare tenkt på det som en fin måte å organisere imports på 🤷‍♂️

2021-01-16 00:02 UTC, Zenjjim commented on src/components/layout/Container.tsx
> +// Material UI Components
Personlig er jeg fan av alfabetisk, da er man garantert at ting som kommer fra samme sted blir satt sammen pga samme pakkenavn. Men om det er ønskelig å skape et tydelig skille er det ikke en dum praksis så lage kommentar som import overskrift

2021-01-16 00:33 UTC, Zenjjim requested changes

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +      reset({ info: { bedrift: '', kontaktperson: '', epost: '' }, comment: '' });
Jeg ville flyttet dette ut i et eget objekt og gitt den en type.

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +  const getSemester = (semester: number) => {
Hahaha kan du ikke bare si at alle oddetall semester er høst og partall er vår???

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +    return returnMonth + ' ' + dateYear;
Backtic string

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +  const getSemester = (semester: number) => {
Og hvis du lurer på hvilket år er det bare å plusse på floor(semester/2)

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +  const semesters = useMemo(() => [0, 1, 2, 3].map(getSemester), []);
Litt fancy, men du kan bytte ut [0,1,2,3] med [...Array(4).keys()]

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +          defaultValue=''
Unødvendig

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +          defaultValue=''
Samme

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +        <TextField
Anbefaler egentlig å bruke textfield komponent som har alt dette, for blir mye repetisjon. Kan se på den som er i Svein sin PR

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/Companies/index.tsx
> +          <div className={classes.grid}>
Enig at dersom man kan css grids, er det bedre enn mu grids. Krever mer forståelse, men er fundamentalt bedre

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +    top: -60,
Hva skjer her???

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +    top: -60,
Ser ikke helt ut som bra css

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +      'radial-gradient(circle at bottom, ' + theme.palette.colors.gradient.secondary.top + ', ' + theme.palette.colors.gradient.secondary.bottom + ')',
Backtic string

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +      setError('username', { type: 'manual', message: 'Bruk brukernavnet på NTNU, ikke en epost-adresse' });
Bruk feide brukernavn, ikke epost...

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +      setError('username', { type: 'manual', message: 'Bruk brukernavnet på NTNU, ikke en epost-adresse' });
Og dette burde bli gjort i react-hook-form ikke i submit funksjonen. Validering skal skje før

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +      setError('username', { type: 'manual', message: 'Bruk brukernavnet på NTNU, ikke en epost-adresse' });
Det gjøres ved å bruke enten pattern eller validate i RHF

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +    setIsLoading(false);
Denne blir jo fjernet etter navigering til nytt vindu. Trenger vel stengt talt kun å kjøre den i catch. Mulig jeg loker helt her

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +    setIsLoading(false);
Denne blir jo fjernet etter navigering til nytt vindu. Trenger vel stengt talt kun å kjøre den i catch. Mulig jeg loker helt her

2021-01-16 00:33 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +          <Grid container direction='column'>
Haha ♥

2021-01-16 07:14 UTC, olros commented on src/containers/Companies/components/CompaniesForm.tsx
> +  const getSemester = (semester: number) => {
Hvordan skal det funke? Til sommeren er jo semester[0] høsten og da partall?

2021-01-16 08:30 UTC, olros commented on src/components/layout/Container.tsx
> +// Material UI Components
Hat du en eslint/prettier pakke som sorterer imports @Zenjjim ? Er veldig med på det

2021-01-16 08:46 UTC, olros commented on src/containers/LogIn/index.tsx
> +    top: -60,
For å flytte login-boksen litt opp over over top-gradienten

![image](https://user-images.githubusercontent.com/31009729/104807480-a3a8bc00-57df-11eb-8049-3060869fe818.png)

2021-01-16 10:16 UTC, Zenjjim commented on src/containers/Companies/components/CompaniesForm.tsx
> +  const getSemester = (semester: number) => {
Ååååå skjønner skjønner

2021-01-16 10:19 UTC, Zenjjim commented on src/components/layout/Container.tsx
> +// Material UI Components
https://eslint.org/docs/rules/sort-imports

2021-01-16 10:26 UTC, Zenjjim commented on src/components/layout/Container.tsx
> +// Material UI Components
https://github.com/benmosher/eslint-plugin-import

2021-01-16 10:39 UTC, Zenjjim approved these changes
To rules som hadde vært nice å ha :

https://www.github.com/yannickcr/eslint-plugin-react/tree/master/docs%2Frules%2Fjsx-sort-props.md

https://www.github.com/yannickcr/eslint-plugin-react/tree/master/docs%2Frules%2Fjsx-max-props-per-line.md

2021-01-16 10:39 UTC, Zenjjim commented on src/containers/LogIn/index.tsx
> +          <TextField errors={errors} label='Passord' name='password' register={register} required rules={{ required: 'Feltet er påkrevd' }} type='password' />
Formater dette på flere linjer er du snill

2021-01-16 11:06 UTC, olros commented on src/containers/LogIn/index.tsx
> +          <TextField errors={errors} label='Passord' name='password' register={register} required rules={{ required: 'Feltet er påkrevd' }} type='password' />
Ta endring av linting i en annen pr

2021-01-16 11:14 UTC, merged