Frontend/feat/about index
tihlde/Kvark pull request #373
Opened 2021-02-08 16:19 UTC by maxschau

## Description

Comments/issues/screenshots:
![image](https://user-images.githubusercontent.com/49594236/107247142-43e5af80-6a31-11eb-9a87-e170112a69a7.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes

## Typescript convert checklist

- [x] All relative imports has been converted to absolute imports
- [x] All HOC's have been replaced with Hooks
- [x] Uses theme.spacing() instead of custom padding
- [x] Uses theme.breakpoints instead of custom media queries

2021-02-08 17:40 UTC, olros requested changes

2021-02-08 17:40 UTC, olros commented on package.json
> +    "react-markdown": "^4.3.1",
Please revert disse endringene

2021-02-08 17:40 UTC, olros commented on src/URLS.tsx
> +  aboutIndex: '/om-tihlde/undergruppe/index',
```suggestion
  aboutIndex: '/om-tihlde/undergruppe/index/',
```

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/ErrorCard.tsx
> +            <MailOutlineIcon className={classes.icons} />
Kanskje bruke forskjellig ikon på Slack og Mail?

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/ErrorCard.tsx
> +import { Box, Grid, makeStyles, Typography } from '@material-ui/core';
Del disse opp i enkelt-imports:
```jsx
import Box from '@material-ui/core/Box';
...
```

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/MembersCard.tsx
> +import { Box, Grid, makeStyles, Typography } from '@material-ui/core';
Del disse opp i enkelt-imports:
```jsx
import Box from '@material-ui/core/Box';
...
```

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/ErrorCard.tsx
> +import React from 'react';
Du trenger ikke importere React

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/MembersCard.tsx
> +import React from 'react';
Ikke importer React

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/MembersCard.tsx
> +const MembersCard = (props: MembersCardProps) => {
Destrukturer `props` her for å gjøre det mer oversiktig
```suggestion
const MembersCard = ({ members }: MembersCardProps) => {
```

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +import React from 'react';
^

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +import { makeStyles, Typography } from '@material-ui/core';
Del opp

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +  const [markdownString, setMarkDownString] = React.useState<string>('');
Importer `useState` fra React istedenfor å bruke `React.useState`. Du trenger ikke deklarere at det er en string type i useState når den initieres med `''`.

Dette bør altså være sånn:
```suggestion
  const [markdownString, setMarkDownString] = useState('');
```

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +  const latestVersionIndex = 3;
Flytte disse utenfor `const WorkDoneCard = [...]` med store bokstaver for å vise at det er konstanter?

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +  React.useEffect(() => {
Importer `useEffect` direkte

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +        setMarkDownString(markdownSections[latestVersionIndex]);
Dette kan slås sammen til en linje
```suggestion
        setMarkDownString(text.split(markdownHeaderDelimiter)[latestVersionIndex]);
```

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/index.tsx
> +import MembersCard from './components/MembersCard';
Bruk absolutte imports

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/index.tsx
> +import { Container, Grid, makeStyles } from '@material-ui/core';
Del opp

2021-02-08 17:40 UTC, olros commented on src/containers/AboutIndex/index.tsx
> +      <Container className={classes.root} maxWidth='xl'>
Legg banner inni `<Navigation banner={<Banner title='Om Index' fancyNavbar>` så slipper du å bruke `Container` for å begrense bredden på siden

2021-02-08 17:40 UTC, olros commented on src/typings.d.ts
> +declare module '*.md' {
Hvorfor trenger du denne?

2021-02-08 17:40 UTC, olros commented on tsconfig.json
> +  ],
^

2021-02-08 17:45 UTC, olros commented
Også bør siden breakes på 600px istedenfor 400px

2021-02-08 18:27 UTC, maxschau commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +        setMarkDownString(markdownSections[latestVersionIndex]);
Det kan det, men jeg synes det er mer lesbart og enklere å forstå slik det står nå.

2021-02-08 18:32 UTC, maxschau commented on src/typings.d.ts
> +declare module '*.md' {
Var fra da jeg hadde lagret en .md fil lokalt for å teste, men jeg glemte å fjerne den

2021-02-08 19:29 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +        setMarkDownString(markdownSections[latestVersionIndex]);
Den er grei 👍

2021-02-09 23:08 UTC, olros requested changes
Lurer litt på om vi skulle fjernet ikonene i overskriftene, synes de blir litt store og bryter også med resten av nettsiden siden vi ikke har gjort det sånn andre steder. I tillegg bør gjenværende ikoner være av type "Rounded"

2021-02-09 23:08 UTC, olros commented on src/containers/AboutIndex/components/MembersCard.tsx
> +import makeStyles from '@material-ui/core/styles/makeStyles';
Trodde ikke Material UI støttet importering fra nivå 3? https://material-ui.com/guides/minimizing-bundle-size/#option-1
```suggestion
import { makeStyles } from '@material-ui/core/styles';
```

2021-02-09 23:08 UTC, olros commented on src/containers/AboutIndex/components/MembersCard.tsx
> +        {members.map((member: string) => {
Bør ikke være nødvendig å si at `member` er en string her, Typescript skjønner det selv
```suggestion
        {members.map((member) => {
```

2021-02-09 23:08 UTC, olros commented on src/containers/AboutIndex/components/WorkDoneCard.tsx
> +  });
Kan endre dette til å bruke React-Query slik at det blir cachet. Kan gjerne vise hvordan

2021-02-09 23:08 UTC, olros commented on src/containers/AboutIndex/index.tsx
> +};
Denne brukes ikke?

2021-02-14 12:50 UTC, olros approved these changes
Nå blir HS happy 🥇

2021-02-14 13:02 UTC, merged