feat(event): giftcard sender
TIHLDE/Kvark pull request #386
Opened 2022-02-17 22:26 UTC by martcl

## Description
Som admin ønsker jeg å sende ut gavekort til deltagere ved et arrangement. Admin kan laste opp PDFer og sende dem ut til deltagerne. Denne pull request følger mesteparten av hva som har blitt gjort i #361, men etter at jeg byttet pakke for drag-and-drop funksjonalitet startet jeg en ny branch for å gjøre livet lettere.

I tillegg har jeg laget en generell fil opplastning komponent som kan brukes flere steder fks i gallery. Jeg la til et siste bilde av hvordan det ville sett ut med bilder @callumgran.
 
closes #334

Changes:
Lager en ny komponent `FileUploader` og en ny knapp i adminpanelet der admin kan laste opp og sende gavekort.

Screenshots:
<img width="905" alt="Skjermbilde 2022-02-17 kl  23 17 14" src="https://user-images.githubusercontent.com/26656069/154580894-51fb1605-cca8-4538-9c7b-6c8add03906c.png">
<img width="912" alt="Skjermbilde 2022-02-17 kl  23 17 20" src="https://user-images.githubusercontent.com/26656069/154580899-6b965667-c5d6-4d00-83c3-293da8314806.png">
<img width="893" alt="Skjermbilde 2022-02-17 kl  23 17 27" src="https://user-images.githubusercontent.com/26656069/154580906-55e29b57-650a-4a69-8b25-ed1b54de9787.png">
<img width="916" alt="Skjermbilde 2022-02-17 kl  23 17 41" src="https://user-images.githubusercontent.com/26656069/154580909-51187a0d-befb-4c71-b71f-9887922efdb7.png">
<img width="952" alt="Skjermbilde 2022-02-17 kl  23 21 05" src="https://user-images.githubusercontent.com/26656069/154580911-aea88779-fa72-4533-a3ce-dd8a70b84bba.png">

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a picture showing visual changes
- [ ] Added Analytics-events if relevant
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2022-02-18 06:28 UTC, olros requested changes
Ser veldig bra ut! Well done!

2022-02-18 06:28 UTC, olros commented on src/components/inputs/FileUploader.tsx
> +    return previewImages.forEach((imageUrl) => typeof imageUrl === 'string' && URL.revokeObjectURL(imageUrl));
Hvorfor returnerer du her?

2022-02-18 06:28 UTC, olros commented on src/components/inputs/FileUploader.tsx
> +                    backgroundSize: 'cover',
```suggestion
                    backgroundSize: 'contain',
```

Tror contain er bedre slik at man ser alt av alle bilder

2022-02-18 06:28 UTC, olros commented on src/components/inputs/FileUploader.tsx
> +  const [previewImages, setPreviewImages] = useState<(string | boolean)[]>([]);
Trenger dette å være en egen state eller kan du heller lage ObjectURL idet filen skal vises frem i .map-funksjonen?

2022-02-18 06:28 UTC, olros commented on src/pages/EventAdministration/components/EventGiftCardSender.tsx
> +  eventId: number;
```suggestion
  eventId: Event['id'];
```

Vet det ikke er gjort mange andre steder, men dette synes jeg er enda mer lesbart

2022-02-18 06:30 UTC, olros commented
Et problem jeg merket nå er at jeg ikke klarer å velge filer ved å klikke på boksen. I hvertfall ikke på mobilen min

2022-02-24 17:29 UTC, martcl commented
Det fungerer på mobil nå

2022-02-24 18:15 UTC, olros requested changes

2022-02-24 18:15 UTC, olros commented on kvark.code-workspace
> +    "editor.formatOnSave": false,
Please revert

2022-02-24 18:15 UTC, olros commented on src/components/inputs/FileUploader.tsx
> +type FileUploaderProps = {
```suggestion
export type FileUploaderProps = {
```

Eksporter props når komponenten som høres til exporteres

2022-02-24 18:15 UTC, olros commented on src/components/inputs/FileUploader.tsx
> +  const ImageURL = useRef(URL.createObjectURL(file));
```suggestion
  const imageURL = useRef(URL.createObjectURL(file));
```

Det er vanligvis kun classes og komponenter som har stor forbokstav

2022-02-25 08:21 UTC, olros approved these changes
Looks good ✉️

2022-02-25 12:07 UTC, merged