Feat(news): news author
TIHLDE/Kvark pull request #431
Opened 2022-03-09 20:05 UTC by martcl

## Description

closes #421

Changes:
Legger til forfatter på nyheter. Forfatteren er klikkbar og fører brukeren til forfatteren sin side på TIHLDE siden.

Screenshots:
<img width="1093" alt="Skjermbilde 2022-03-09 kl  20 58 20" src="https://user-images.githubusercontent.com/26656069/157523883-3ed269d3-7d43-422a-85c6-fccfe7dd2a65.png">
<img width="1086" alt="Skjermbilde 2022-03-09 kl  20 58 32" src="https://user-images.githubusercontent.com/26656069/157523891-c3c22a00-9196-4739-ba0c-5b3734e71d7b.png">
<img width="1016" alt="Skjermbilde 2022-03-09 kl  20 58 48" src="https://user-images.githubusercontent.com/26656069/157523895-c4d5aa57-fbcf-4624-8679-8b405e246191.png">
<img width="992" alt="Skjermbilde 2022-03-09 kl  21 02 44" src="https://user-images.githubusercontent.com/26656069/157524404-d4cbe147-fef6-40cf-a602-4d40b6edd9fa.png">

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The PR includes a picture showing visual changes
- [ ] Added Analytics-events if relevant
- [x] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2022-03-09 20:52 UTC, martcl commented
Ser ingen metode i backend for å endre forfatter på artikler, det bør i hvert fall legges til før denne merges.

2022-03-10 23:40 UTC, callumgran commented
Det eneste jeg kan tenke er at det hadde kanskje vært greit med mulighet for anonym forfatter, ellers synes jeg alt så bra ut. Eneste jeg lurte på er i kommentaren agående async await.

2022-03-11 08:22 UTC, olros requested changes

2022-03-11 08:22 UTC, olros commented on src/pages/NewsAdministration/components/NewsEditor.tsx
> +            required
Den er ikke required. Vi må også fikse at en ikke kan endre forfatter senere, så hjelpeteksten kan vel da egentlig fjernes
```suggestion
            label='Forfatter'
            name='creator'
```

2022-03-11 08:22 UTC, olros commented on src/pages/NewsDetails/components/NewsRenderer.tsx
>            </Stack>
Kan jeg foreslå en slik løsning med bare en link til forfatter:
```suggestion
          <Stack alignItems='center' direction='row' justifyContent='space-between'>
            <Stack>
              <Typography variant='body2'>Publisert: {formatDate(parseISO(data.created_at), { time: false })}</Typography>
              {data.creator && (<Typography variant='body2'>Forfatter: <Link to={`${URLS.profile}${data.creator.user_id}/`}>{data.creator.first_name} {data.creator.last_name}</Link></Typography>)}
            </Stack>
            <ShareButton shareId={data.id} shareType='news' title={data.title} />
          </Stack>
```

2022-03-12 14:59 UTC, olros approved these changes
Endret noe på utseende av NewsRenderer:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/31009729/158023081-9549e9a1-529d-4b92-89f8-26cf0d29ab45.png">

Tanker?

Fikset også UserSearch slik at verdien i den oppdateres ved endring utenfra (for eksempel ved bytting av vist nyhet i admin)

2022-03-12 16:20 UTC, martcl commented
Nice virker bra! Er på jobb må se på koden i morgen, men det hadde vært fint å vise profilbilde til forfatteren et eller annet sted.

2022-03-13 13:36 UTC, merged