feat(calendar): popup on click
TIHLDE/Kvark pull request #437
Opened 2022-03-13 10:44 UTC by MinhdanNg

## Description
Når man klikker på et arrangement i kalender vil det poppe opp en informasjonsboks.
Kalenderen er også lagt til i arrangementsiden.

closes #143 

Changes:
Popup ved klikk på arrangement
Kalender i arrangementsiden

Screenshots:
![image](https://user-images.githubusercontent.com/70275130/158055672-f0a24c04-3bf3-491d-9b91-f49b5511e974.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a picture showing visual changes
- [ ] Added Analytics-events if relevant
- [ ] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2022-03-13 11:02 UTC, callumgran requested changes
Ser bra ut for det meste det her!

2022-03-13 11:25 UTC, MinhdanNg commented on src/pages/Landing/components/EventsCalendarPopover.tsx
> +        <div style={{ width: '210px' }}></div>
Jeg returnerte egentlig null, men da blir den seende sånn ut før jeg beveger på siden:
![image](https://user-images.githubusercontent.com/70275130/158057102-a7ce819f-b0a3-4a12-b056-70d86c0a3c2e.png)

Tror dette er fordi den bruker posisjonen til null, før den oppdaterer til den nye størrelsen på boksen. I stedet returnerer jeg en div som har ca. bredden til den ferdige boksen. Dette er egentlig et desperat forsøk på å fikse den lille feilen og er på ingen måte perfekt.

2022-03-13 11:39 UTC, callumgran commented
Har du forresten kjørt yarn i det siste/hatt problemer med prettier? Ser det er en del små problemer på siste pushen din som prettier pleier å automatisk fikse.

2022-03-17 16:29 UTC, olros requested changes

2022-03-17 16:29 UTC, olros commented on src/pages/Events/index.tsx
> +// Project componets/services
Fjern kommentar

2022-03-17 16:29 UTC, olros commented on src/pages/Events/index.tsx
> +// Icons
Fjern kommentar

2022-03-17 16:29 UTC, olros commented on src/pages/Landing/components/EventsCalendarPopover.tsx
> +// Project components
Fjern kommentar

2022-03-17 16:29 UTC, olros commented on src/pages/Landing/components/EventsCalendarPopover.tsx
> +  );
Istedenfor å bruke DetailsPaper med egen grid styling, så kan du heller bruke Stack med Paper som component. Legg i tillegg `data !== undefined`-sjekken inni så slipper du kanskje den tomme div'en med width

```suggestion
  return (
    <Stack component={Paper} gap={1} sx={{ minWidth: 210, py: 1, px: 2 }}>
      {data && (
        <>
          <DetailsHeader variant='h2'>Detaljer</DetailsHeader>
          <DetailContent info={formatDate(parseISO(data.start_date))} title='Fra:' />
          <DetailContent info={formatDate(parseISO(data.end_date))} title='Til:' />
          <DetailContent info={data.location} title='Sted:' />
          <DetailsHeader variant='h2'>Påmelding</DetailsHeader>
          <DetailContent info={`${data.list_count}/${data.limit}`} title='Påmeldte:' />
          <DetailContent info={String(data.waiting_list_count)} title='Venteliste:' />
          <Link to={`${URLS.events}${data.id}/${urlEncode(data.title)}/`}>Til arrangement</Link>
        </>
      )}
    </Stack>
  );
```

2022-03-17 16:29 UTC, olros commented on src/pages/Events/components/EventsDefaultView.tsx
> +    <Page>
Her blir det Page inne i en annen Page, unngå det
```suggestion
    <>
```

2022-03-17 16:29 UTC, olros commented on src/pages/Landing/components/EventsCalendarView.tsx
> +    <div>
Må det være en div rundt eller kan du bruke <>?
```suggestion
    <>
```

2022-03-17 16:29 UTC, olros commented on src/pages/Landing/components/EventsCalendarView.tsx
> +      <div onClick={handleClick}>
Man bør aldri legge onClick rett på en vanlig div. Da vil ikke skjermlesere og andre som har bruk for universell utforming kunne bruke onClick-funksjonen fordi pc'en ikke oppdager den. Se om du kan bruke <ButtonBase /> eller vanlig <button /> istedenfor

2022-03-17 16:29 UTC, olros commented on src/pages/Landing/components/EventsCalendarView.tsx
> +          <div>{typeof data.id === 'number' ? <EventsCalendarPopover id={data.id} /> : null}</div>
Vi vet at data.id faktisk alltid vil være et tall derfor kan du gjøre følgende (tror jeg)
```suggestion
          <EventsCalendarPopover id={Number(data.id)} />
```

2022-04-29 06:56 UTC, olros requested changes
Hvis jeg klikker på flere etter hverandre så åpnes det nye bokser uten at de forrige lukkes, tror det er mer intuitivt om bokser lukkes ved klikk utenfor:

![image](https://user-images.githubusercontent.com/31009729/165897480-db92aa45-5044-4835-bbf0-080fead50a67.png)

2022-04-29 06:56 UTC, olros commented on src/pages/Events/components/EventsDefaultView.tsx
> +    <Page banner={<Banner title='Arrangementer' />} options={{ title: 'Arrangementer' }}>
Når er det dobbelt opp med `<Page>`. Du kan egentlig bare fjerne Page her så bør det fungere:

![image](https://user-images.githubusercontent.com/31009729/165897671-8870fa02-b355-4d8d-9e3c-520281fb4819.png)

2022-04-29 06:56 UTC, olros commented on src/pages/Landing/components/EventsCalendarPopover.tsx
> +export type PopoverProps = {
```suggestion
export type EventsCalendarPopoverProps = {
```

2022-04-29 06:56 UTC, olros commented on src/pages/Landing/components/EventsCalendarView.tsx
> +import EventsCalendarPopover from './EventsCalendarPopover';
Bruk absolutt import
```suggestion
import EventsCalendarPopover from 'pages/Landing/components/EventsCalendarPopover';
```

2022-05-12 16:24 UTC, olros approved these changes
Herlig!

2022-05-12 16:25 UTC, merged