fix(fines): Made button action more intuitive
TIHLDE/Kvark pull request #451
Opened 2022-03-17 16:42 UTC by trthingnes

## Description
Made the buttons in the Fine elements say what the button does. Previously the state of the fine has been displayed.

Screenshots:
![image](https://user-images.githubusercontent.com/24162884/158849616-64b90734-6ca4-4813-b619-374968b219fb.png)

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The PR includes a picture showing visual changes
- [ ] Added Analytics-events if relevant
- [x] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2022-03-17 16:51 UTC, callumgran approved these changes

2022-03-17 16:53 UTC, olros requested changes

2022-03-17 16:53 UTC, olros commented on src/pages/Groups/fines/FineItem.tsx
> +          </Tooltip>
Ikke helt enig i at disse skal flyttes ut fra ListItemText, blir lite plass igjen til navn på person og lov som er brutt. Dette er på iPhone 12 pro: 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/31009729/158852313-677f4cea-3120-433f-acd5-38b9b83d0262.png">

2022-03-17 16:53 UTC, olros commented on src/pages/Groups/fines/FineItem.tsx
> +                  {fine.approved ? 'Merk som ikke godkjent' : 'Merk som godkjent'}
Synes det burde være contained slik at noen av knappene står mer ut enn andre. Da veileder vi bruker til hva som skal klikkes på
```suggestion
                  variant='contained'>
                  Merk som {fine.approved ? 'ikke godkjent' : 'godkjent'}
```

2022-03-17 16:53 UTC, olros commented on src/pages/Groups/fines/FineItem.tsx
> +                  {fine.payed ? 'Merk som ubetalt' : 'Merk som betalt'}
```suggestion
                  variant='contained'>
                  Merk som {fine.payed ? 'ikke betalt' : 'betalt'}
```

2022-03-18 11:45 UTC, olros requested changes

2022-03-18 11:45 UTC, olros commented on src/pages/Groups/fines/FineItem.tsx
> +          </Stack>
Chip for status på betaling og godkjent-status er en god idé! Men å bruke chips til den andre informasjonen er ikke særlig lurt. Det er ikke intuitivt at chip med navn er den som opprettet bot, og reason kan potensielt være langt og passer dermed ikke i en chip. I tillegg er det nok fint med en farge på de 2 chip'ene som blir stående igjen
```suggestion
          <Stack direction='row' gap={1}>
            <Chip color={fine.approved ? 'success' : 'error'} icon={<ApprovedIcon />} label={fine.approved ? 'Godkjent' : 'Ikke godkjent'} variant='outlined' />
            <Chip color={fine.payed ? 'success' : 'error'} icon={<PaidIcon />} label={fine.payed ? 'Betalt' : 'Ikke betalt'} variant='outlined' />
          </Stack>
          <div>
            {fine.reason && <Typography variant='subtitle2'>{`Begrunnelse: ${fine.reason}`}</Typography>}
            <Typography variant='subtitle2'>{`Opprettet av: ${fine.created_by.first_name} ${fine.created_by.last_name}`}</Typography>
            <Typography variant='subtitle2'>{`Dato: ${formatDate(parseISO(fine.created_at), { fullDayOfWeek: true, fullMonth: true })}`}</Typography>
          </div>
```

2022-03-18 11:45 UTC, olros commented on src/pages/Groups/fines/FineItem.tsx
> +                  {fine.approved ? 'Merk som ikke godkjent' : 'Merk som godkjent'}
Tanker? ^

2022-03-18 11:45 UTC, olros commented on src/pages/Groups/fines/FineItem.tsx
> +                  {fine.payed ? 'Merk som ubetalt' : 'Merk som betalt'}
Tanker? ^

2022-03-24 17:02 UTC, olros approved these changes

2022-03-24 17:21 UTC, merged