feat(group-overview): added group overview
TIHLDE/Kvark pull request #47
Opened 2021-03-22 16:29 UTC by SveinJH

## Description
Inital work on the new groups system. Added an overview page that displays the groups and their leader, fetched from the DB. Also added a shortcut to this page in the 'For medlemmer' dropdown, and in the admin tab in your profile. Also sorted the tabs in alphabetical order.

Comments/issues/screenshots:
![image](https://user-images.githubusercontent.com/43957538/112023812-e23a5a00-8b33-11eb-9d96-82b1ed1991a3.png)
-----
![image](https://user-images.githubusercontent.com/43957538/112023861-ebc3c200-8b33-11eb-94d1-4f6b5e862730.png)
-----
![image](https://user-images.githubusercontent.com/43957538/112023905-f716ed80-8b33-11eb-885e-53587b665a18.png)

closes #9

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes

2021-03-22 19:08 UTC, olros requested changes
Well done 🚀  Siden krasjet når keg åpnet den i Vercel, vet ikke hvorfor? Og ser at det er veldig mye setting av custom fontSize. Er best å holde det uendret så mye som mulig og heller bruke de som ligger der by default i theme

2021-03-22 19:08 UTC, olros commented on src/containers/GroupOverview/index.tsx
> +        <Typography className={[classes.marginMed, classes.title].join(' ')} variant='h1'>
Du kan bruke classnames-pakken for å legge flere classes på samme element

2021-03-22 19:08 UTC, olros commented on src/containers/GroupOverview/index.tsx
> +import GroupItem from './components/GroupItem';
Absolutt import

2021-03-22 19:08 UTC, olros commented on src/containers/GroupOverview/index.tsx
> +import { PersonListItemLoading } from 'containers/UserAdmin/components/PersonListItem';
Litt rart å bruke denne når det som vises etter at lasting er ferdig ikke har samme layout

2021-03-22 19:08 UTC, olros commented on src/containers/GroupOverview/components/GroupItem.tsx
> +    marginLeft: '.3rem',
Bruk theme.spacing

2021-03-22 19:08 UTC, olros commented on src/containers/GroupOverview/components/GroupItem.tsx
> +    cursor: 'pointer',
Istedenfor å gjøre en div clickable så bør du heller bruke for eks et <Card /> fra Material UI som har ripple effekt og faktisk er en knapp. Der er viktig for universell utforming og at det blir likt som resten av siden. Andre alternativer er ListItem og Button

2021-03-22 19:08 UTC, olros commented on src/components/navigation/Topbar.tsx
> -                { text: 'Link-forkorter', to: URLS.shortLinks },
Hvorfor er denne fjernet?

2021-03-22 19:08 UTC, olros commented on src/api/hooks/Group.tsx
> +export const useGroups = (filters?: any) => {
Ut ifra bruken ser det ikke ut som at filtrering brukes. Er det mulig å filtrere? Hvis ikke så kan dette bare fjernes

2021-03-22 19:08 UTC, olros commented on src/api/hooks/Group.tsx
> +};
Hvorfor undefined?

2021-03-22 19:08 UTC, olros commented on src/URLS.tsx
> +  groups: '/grupper',
```suggestion
  groups: '/grupper/',
```

Alltid / på slutten av url'er ;)

2021-03-23 07:04 UTC, SveinJH commented on src/containers/Profile/components/ProfileAdmin.tsx
> +            Administrer nyheter
Alfabetisk rekkefølge, men om det skal være i den rekkefølgen det var, bytter jeg tilbake :)

2021-03-23 07:07 UTC, SveinJH commented on src/components/navigation/Topbar.tsx
> -                { text: 'Link-forkorter', to: URLS.shortLinks },
Branchen min hadde tydeligvis ikke siste updates fra dev, så ble no greier der..

2021-03-23 11:24 UTC, olros commented on src/containers/Profile/components/ProfileAdmin.tsx
> +            Administrer nyheter
Åja, kan gjerne sortere ja. Bare lurte :)

2021-03-26 19:51 UTC, maxschau commented
Hvorfor skal ikke denne være åpen for folk som ikke er medlem? Er ikke tanken at dette skal være et slags organisasjonskart? I så fall bør det være tilgjengelig for allmenheten

2021-03-27 21:27 UTC, olros commented
Klarer ikke helt bestemme meg for hva jeg tror er best ift om det skal være åpent for alle eller ikke. Hvis alle kan se alle grupper, blir det ikke da litt rart med medlemsoversikt også i pages? Men forsåvidt enig i at det gir mening å lage et organisasjonskart ut av dette.

Planen først var at dette skulle være kun for admin og at pages skulle ta seg av oversikten for andre, men når alle vil se hvilke grupper de er med i samt hvem andre er med i, så gir det mening å åpne opp for alle ja. Må bare unngå å vise frem grupper som for eks TIHLDE-gruppa som basically er alle brukere.

2021-03-28 13:07 UTC, maxschau commented
Ja nei jeg merker jeg er veldig usikker selv

2021-04-25 09:47 UTC, olros requested changes

2021-04-25 09:47 UTC, olros commented on src/containers/GroupOverview/components/GroupItem.tsx
> +    borderRadius: 10,
```suggestion
    border: `${theme.palette.borderWidth} solid ${theme.palette.divider}`,
    borderRadius: theme.shape.borderRadius,
```

2021-04-25 09:47 UTC, olros commented on src/containers/GroupOverview/components/GroupItem.tsx
> +      <Typography className={classes.group} variant='h6'>
Unngå å bruke heading som er mindre enn h3 pga WCAG

2021-04-25 09:47 UTC, olros commented on src/containers/GroupOverview/index.tsx
> +        <Typography className={[classes.marginMed, classes.title].join(' ')} variant='h1'>
```suggestion
        <Typography className={classnames(classes.marginMed, classes.title)} variant='h1'>
```

2021-04-25 09:47 UTC, olros commented on src/types/Types.tsx
> +  leader: Partial<User>;
Denne bør types med strict med akkurat hva som er i User, for eks:
```suggestion
  leader: Pick<User, 'user_id' | 'first_name' | 'last_name'>;
```

Hvis ikke vil man måtte sjekke hver gang man bruker user.* om fieldet er undefined eller ikke

2021-04-26 17:13 UTC, merged