feat(show members): Added feature
TIHLDE/Kvark pull request #53
Opened 2021-03-26 20:36 UTC by maxschau

## Description

Each of the sections under "undergrupper" will now display the members from the database. If there are no leader and no members the member card will not be rendered. It will also display a bit different dependent on whether there is a leader from the database or members (see screenshots). 

Comments/issues/screenshots:

![image](https://user-images.githubusercontent.com/49594236/112689567-c65bee80-8e7a-11eb-95ac-c497a1e79d0a.png)

![image](https://user-images.githubusercontent.com/49594236/112689599-d1168380-8e7a-11eb-8968-6cda2d6b3e77.png)

![image](https://user-images.githubusercontent.com/49594236/112689632-da075500-8e7a-11eb-8583-ebfd2becce28.png)

closes #31 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes

2021-03-27 21:22 UTC, olros requested changes

2021-03-27 21:22 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +  if (!members) {
Kanskje bruke `isLoading` fra useMemberships istedenfor. Litt mer forklarende

2021-03-27 21:22 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +    return <Skeleton height='100px' variant='rect' />;
Legge denne inni et Paper?

2021-03-27 21:22 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +  if (members.length === 0 && !leader) {
```suggestion
  if (!members.length && !leader) {
```

2021-03-27 21:22 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +          <>
Denne <> er overflødig siden <Grid> er eneste element inni

2021-03-27 21:22 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +            <>
```suggestion
        {members.map((member) => (
```

2021-03-28 13:50 UTC, olros requested changes

2021-03-28 13:50 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +        {members && members.length > 0 && (
```suggestion
        {members?.length > 0 && (
```

2021-03-28 13:50 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +        )}
```suggestion
        {leader && (
          <Grid item xs={12}>
            <Typography variant='subtitle1'>
              <b>Leder:</b>
            </Typography>
            <Box alignItems='center' display='flex' flexWrap='wrap'>
              <StarIcon className={classes.icons} />
              <Typography variant='subtitle1'>{`${leader?.user.first_name} ${leader?.user.last_name}`}</Typography>
            </Box>
          </Grid>
        )}
```

2021-03-30 09:09 UTC, maxschau commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +        {members && members.length > 0 && (
Får ikke gjort dette da members kan være undefined

2021-04-25 09:48 UTC, olros commented
Kan denne closes pga #55 ? Ser ut som funksjonalitet her har blitt med i den.

2021-04-25 11:16 UTC, maxschau commented
> Kan denne closes pga #55 ? Ser ut som funksjonalitet her har blitt med i den.

Ja I guess. Denne var jo ment for pages, men er vel egentlig ikke så nøye når vi får inn gruppeoversikten

2021-04-26 17:13 UTC, closed without merging