Feat/group admin
TIHLDE/Kvark pull request #55
Opened 2021-03-29 18:49 UTC by maxschau

## Description

Comments/issues/screenshots:

closes #

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a `closes #issueID`
- [ ] The PR includes a picture showing visual changes

2021-04-20 16:38 UTC, olros requested changes

2021-04-21 12:45 UTC, Zenjjim requested changes

2021-04-21 12:45 UTC, Zenjjim commented on src/URLS.tsx
> +  NOK: 'tihlde/undergrupper/nringsliv-og-kurs/',
```suggestion
  NOK: 'tihlde/undergrupper/naeringsliv-og-kurs/',
```

2021-04-21 12:45 UTC, Zenjjim commented on src/containers/GroupAdmin/components/AddMemberModal.tsx
> +    const filters: Record<string, any> = {};
```suggestion
    const filters: Record<string, unknown> = {};
```

?? tror det er dette som er riktig

2021-04-21 12:45 UTC, Zenjjim commented on src/containers/GroupAdmin/components/AddMemberModal.tsx
> +
??

2021-04-21 13:52 UTC, maxschau commented on src/URLS.tsx
> +  NOK: 'tihlde/undergrupper/nringsliv-og-kurs/',
Kan itj pga. Slugify :((

2021-04-25 09:40 UTC, olros requested changes
En del småting :)

2021-04-25 09:40 UTC, olros commented on src/api/fetch.tsx
> +type RequestMethodType = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
Siden det var PUT som ble brukt så trenger vi heller ikke legge til PATCH her

2021-04-25 09:40 UTC, olros commented on src/api/hooks/Group.tsx
> +const QUERY_KEY = 'group';
```suggestion
const GROUPS_QUERY_KEY = 'groups';
```
Du kan kombinere disse til 1 `GROUPS_QUERY_KEY`

2021-04-25 09:40 UTC, olros commented on src/api/api.tsx
> +  updateGroup: (data: Group) => IFetch<Group>({ method: 'PUT', url: `group/${data.slug}/`, data }),
```suggestion
  updateGroup: (slug: string, data: Partial<Group>) => IFetch<Group>({ method: 'PUT', url: `group/${slug}/`, data }),
```

Tror det er bedre å dele opp slug og data, samt gjøre data til Partial slik at man kan sende inn oppdatering av kun beskrivelse hvis man ønsker det (sjekk med backend at de tillater delvis PUT).

2021-04-25 09:40 UTC, olros commented on src/api/api.tsx
> +    IFetch<Membership>({ method: 'PUT', url: `group/${slug}/membership/${user_id}/`, data }),
Bruk camelCase
```suggestion
  createMembership: (slug: string, userId: string) =>
    IFetch<Membership>({ method: 'POST', url: `group/${slug}/membership/`, data: { user: { user_id: userId} } }),
  deleteMembership: (slug: string, userId: string) => IFetch<RequestResponse>({ method: 'DELETE', url: `group/${slug}/membership/${userId}/` }),
  updateMembership: (slug: string, userId: string, data: { membership_type: MembershipType }) =>
    IFetch<Membership>({ method: 'PUT', url: `group/${slug}/membership/${userId}/`, data }),
```

2021-04-25 09:40 UTC, olros commented on src/api/hooks/Group.tsx
> +  return useQuery<Group>([QUERY_KEY, slug], () => API.getGroup(slug));
```suggestion
  return useQuery<Group, RequestResponse>([QUERY_KEY, slug], () => API.getGroup(slug));
```

2021-04-25 09:40 UTC, olros commented on src/api/hooks/Group.tsx
> +  return useMutation((group) => API.updateGroup(group), {
Ref slug og Partial<Group> i api
```suggestion
export const useUpdateGroup = (slug: string): UseMutationResult<Group, RequestResponse, Partial<Group>, unknown> => {
  const queryClient = useQueryClient();

  return useMutation((group) => API.updateGroup(slug, group), {
```

2021-04-25 09:40 UTC, olros commented on src/api/hooks/Membership.tsx
>  const QUERY_KEY = 'membership';
```suggestion
export const MEMBERSHIP_QUERY_KEY = 'membership';
```

Eksporter slik at andre filer kan invalidere membership-cache om nødvendig

2021-04-25 09:40 UTC, olros commented on src/api/hooks/Membership.tsx
> +  return useMutation(({ slug, user }) => API.createMembership(slug, user.user_id), {
```suggestion
export const useCreateMembership = (): UseMutationResult<Membership, RequestResponse, { slug: string; userId: string }, unknown> => {
  const queryClient = useQueryClient();
  return useMutation(({ slug, userId }) => API.createMembership(slug, userId), {
```

Noe grunn til at man må sende inn hele User hvis du kun trenger userId? Ville muligens også endret `slug` til `groupSlug` for å lettere forstå at det er slug til gruppe som er nødvendig

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/components/MemberListItem.tsx
> +      )}
Bør ikke være nødvendig å legge Dialogene inne i conditional rendering
```suggestion
        <Dialog
          onClose={handleClose}
          onConfirm={removeMemberFromGroup}
          open={confirmDeleteModal}
          titleText={`Fjern ${user.first_name} ${user.last_name} fra gruppen?`} />
        <Dialog
          onClose={handleClose}
          onConfirm={promoteUserToLeader}
          open={confirmSwitchLeader}
          titleText={`Promoter ${user.first_name} ${user.last_name} til leder?`} />
```

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/components/MemberListItem.tsx
> +      <ListItem button onClick={() => setExpanded(!expanded)}>
Bedre practice pga hooks er async:
```suggestion
      <ListItem button onClick={() => setExpanded((prev) => !prev)}>
```

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/components/UpdateGroupModal.tsx
> +      />
Bruk eget TextField som ligger i `components/inputs/TextField`. Det fikser mye av dette by default

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/components/UpdateGroupModal.tsx
> +        className={classes.gutterBottom}
Textfield har en `margin='normal'`-prop som legger til margin og det får du by default med vår egen TextField-komponent

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/components/UpdateGroupModal.tsx
> +  },
Denne brukes ikke

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/index.tsx
> +  const hasWriteAcccess = data?.permissions.write;
Denne blir vel undefined når data er undefined? Da bør du heller legge den i Boolean() slik at det alltid er en boolean
```suggestion
  const hasWriteAcccess = Boolean(data?.permissions.write);
```

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/index.tsx
> +  const [modalIsOpen, setModalIsOpen] = useState(false);
Kan gi bedre navn her

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/index.tsx
> +  };
Disse kan fjernes også kan du heller bare kalle `setModalIsOpen` og `setAddMemberModalIsOpen` direkte.

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/index.tsx
> +  const params = useParams();
Du kan hente slug ut direkte herfra
```suggestion
  const { slug } = useParams();
```

2021-04-25 09:40 UTC, olros commented on src/containers/GroupAdmin/index.tsx
> +      {isLoadingGroups || isLoadingMembers ? (
```suggestion
      {isLoadingGroups || isLoadingMembers || !data || !membersSorted ? (
```
Legg til sjekk her så slipper du optional chaining når du bruker dem lenger nede

2021-04-25 09:40 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +  const membersSorted = sortBy(members, ['user.first_name', 'user.last_name']);
Erstatt sortBy fra lodash med tilsvarende sortering som ble foreslått lenger oppe:

~~~
members.sort((a, b) => `${a.first_name} ${a.last_name}`.localeCompare(`${b.first_name} ${b.last_name}`))
~~~

2021-04-25 09:40 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +        )}
```suggestion
        {leader && (
            <Grid item xs={12}>
              <Typography variant='subtitle1'>
                <b>Leder:</b>
              </Typography>
              <Box alignItems='center' display='flex' flexWrap='wrap'>
                <StarIcon className={classes.icons} />
                <Typography variant='subtitle1'>{`${leader?.user.first_name} ${leader?.user.last_name}`}</Typography>
              </Box>
            </Grid>
        )}
```

2021-04-25 09:40 UTC, olros commented on src/containers/Pages/specials/Index/index.tsx
>        <WorkDoneCard changelogURL={'https://raw.githubusercontent.com/tihlde/Lepton/dev/CHANGELOG.md'} title={'Hva har vi gjort i backend?'} />
Ikke en del av denne pr'en egentlig, men vi bør vise changelog som ligger i master istedenfor dev
```suggestion
      <WorkDoneCard changelogURL={'https://raw.githubusercontent.com/tihlde/Kvark/master/CHANGELOG.md'} title={'Hva har vi gjort i frontend?'} />
      <WorkDoneCard changelogURL={'https://raw.githubusercontent.com/tihlde/Lepton/master/CHANGELOG.md'} title={'Hva har vi gjort i backend?'} />
```

2021-04-25 09:40 UTC, olros commented on yarn.lock
> +
Fjern import av lodash med `yarn remove lodash`

2021-04-25 11:06 UTC, maxschau commented on src/api/api.tsx
> +  updateGroup: (data: Group) => IFetch<Group>({ method: 'PUT', url: `group/${data.slug}/`, data }),
Virker ikke som det er tillatt dessverre

2021-04-25 11:10 UTC, maxschau commented on src/api/api.tsx
> +  updateGroup: (data: Group) => IFetch<Group>({ method: 'PUT', url: `group/${data.slug}/`, data }),
Det er vel derfor vi ville brukt Patch...

2021-04-25 11:12 UTC, maxschau commented on src/api/api.tsx
> +  updateGroup: (data: Group) => IFetch<Group>({ method: 'PUT', url: `group/${data.slug}/`, data }),
Virker ikke som det er tillatt

2021-04-26 15:32 UTC, olros commented on src/containers/GroupAdmin/index.tsx
> +              {membersSorted && membersSorted.map((member) => <MemberListItem key={member.user_id} slug={slug} user={member} />)}
`membersSorted` er ikke undefined pga sjekken på linje 52
```suggestion
              {membersSorted.map((member) => <MemberListItem key={member.user_id} slug={slug} user={member} />)}
```

2021-04-26 15:32 UTC, olros commented on src/containers/Pages/specials/Index/MembersCard.tsx
> +import { sortBy } from 'lodash';
lodash

2021-04-26 15:32 UTC, olros commented on src/index.tsx
> +import GroupAdmin from 'containers/GroupAdmin/index';
import denne lazy på samme måte som UserAdmin

2021-04-26 18:18 UTC, Zenjjim approved these changes

2021-04-26 18:39 UTC, merged