disabled switch to change from free to paid event if an event has reg…
TIHLDE/Kvark pull request #910
Opened 2023-10-17 18:17 UTC by MadsNyl

…istrations

## Description

This refactor will fix the follwoing issues:

- You can now switch from free to paid event (and vice versa) when there are none registered users, but not when there are.
- You will not be creating a payment order until you press the vipps button. Therefore you will get a new order every time you press the button. This will prevent session timeouts.
- When you unregister from an event after you have paid, your registration will be deleted and you will get refunded your money. This will be notified in the snackbar, and in notifications and with mail. Therefore you will have to pay again if you register again.

closes #

Changes:

Screenshots:

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The PR includes a picture showing visual changes
- [ ] Added Analytics-events if relevant
- [x] CHANGELOG.md has been updated. [Guide](https://tihlde.slab.com/posts/changelog-z8hybjom)

2023-10-17 18:42 UTC, martcl approved these changes

2023-10-17 18:42 UTC, martcl commented on src/pages/EventAdministration/components/EventEditor.tsx
> +            disabled={data?.list_count ? data.list_count > 0 : false}
> Props should be sorted alphabetically

I tillegg:

```suggestion
            disabled={data?.list_count ? data.list_count > 0}
```

2023-10-17 19:17 UTC, martcl requested changes

2023-10-17 19:17 UTC, martcl commented on CHANGELOG.md
> +## versjon 2023.17.10
Ikke skriv versjon selv. Det fikses når vi lanserer i prod

2023-10-17 19:17 UTC, martcl commented on src/pages/EventAdministration/components/EventEditor.tsx
> +            disabled={!(data?.list_count && data?.list_count > 0)}
Jeg tror dette fungerer altså, men kanskje det er noe typescript wodo som foregår
```suggestion
            disabled={data?.list_count && data.list_count > 0}
```

2023-10-17 19:19 UTC, MadsNyl commented on src/pages/EventAdministration/components/EventEditor.tsx
> +            disabled={!(data?.list_count && data?.list_count > 0)}
Ja funker nok, men TS klager på det hvis jeg ikke tar ! foran

2023-10-17 19:21 UTC, martcl commented on src/pages/EventAdministration/components/EventEditor.tsx
> +            disabled={!(data?.list_count && data?.list_count > 0)}
Det å ta utropstegn forran gjør akkuratt motsatt av det vi ønsker. Nå vil den være disabled når vi ikke har deltagere, mens enabled når vi har deltagere

2023-10-18 11:38 UTC, MadsNyl commented on src/pages/EventAdministration/components/EventEditor.tsx
> +            disabled={!(data?.list_count && data?.list_count > 0)}
Jupp har fiksa nå

2023-10-18 11:39 UTC, MadsNyl commented on CHANGELOG.md
> +## versjon 2023.17.10
Fikset nå

2024-01-09 18:31 UTC, merged